"""Model abstract factory."""

from siriuspy.pwrsupply.pru import Const as _PRUConst
from siriuspy.pwrsupply.psmodel import PSModelFactory as _PSModelFactory


class _PRUCParms:
    """PRUC parameters.

    Namespace to group useful parameters used by PRUController.
    """

    # group ids
    ALL = 0
    READONLY = 1
    WRITEABLE = 2
    ALLRELEVANT = 3
    SYNCOFF = 4
    MIRROR = 5

    SLOWREF = SYNCOFF
    MIGWFM = MIRROR
    CYCLE = SYNCOFF
    RMPWFM = MIRROR

    PRU = _PRUConst


class PRUCParmsFBP(_PRUCParms):
    """FBP-specific PRUC parameters."""

    FREQ_RAMP = 2.0  # [Hz]
    FREQ_SCAN = 10.0  # [Hz]

    # PS model parms
    model = _PSModelFactory.create('FBP')
    CONST_PSBSMP = model.bsmp_constants
    Entities = model.entities

    groups = dict()
    # reserved variable groups (not to be used)
    groups[_PRUCParms.ALL] = tuple(sorted(Entities.list_variables(0)))
    groups[_PRUCParms.READONLY] = tuple(sorted(Entities.list_variables(1)))
    groups[_PRUCParms.WRITEABLE] = tuple(sorted(Entities.list_variables(2)))
    # new variable groups useful for PRUController.
    groups[_PRUCParms.ALLRELEVANT] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_FIRMWARE_VERSION,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        CONST_PSBSMP.V_SIGGEN_ENABLE,
        CONST_PSBSMP.V_SIGGEN_TYPE,
        CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        CONST_PSBSMP.V_SIGGEN_N,
        CONST_PSBSMP.V_SIGGEN_FREQ,
        CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        CONST_PSBSMP.V_SIGGEN_OFFSET,
        CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        CONST_PSBSMP.V_WFMREF_SELECTED,
        CONST_PSBSMP.V_WFMREF_SYNC_MODE,
        CONST_PSBSMP.V_WFMREF_GAIN,
        CONST_PSBSMP.V_WFMREF_OFFSET,
        CONST_PSBSMP.V_WFMREF0_START,
        CONST_PSBSMP.V_WFMREF0_END,
        CONST_PSBSMP.V_WFMREF0_IDX,
        CONST_PSBSMP.V_WFMREF1_START,
        CONST_PSBSMP.V_WFMREF1_END,
        CONST_PSBSMP.V_WFMREF1_IDX,
        # --- FBP variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_I_LOAD,
        CONST_PSBSMP.V_V_LOAD,
        CONST_PSBSMP.V_V_DCLINK,
        CONST_PSBSMP.V_TEMP_SWITCHES,
        CONST_PSBSMP.V_DUTY_CYCLE,)
    groups[_PRUCParms.SYNCOFF] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        CONST_PSBSMP.V_SIGGEN_ENABLE,
        CONST_PSBSMP.V_SIGGEN_TYPE,
        CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        CONST_PSBSMP.V_SIGGEN_N,
        CONST_PSBSMP.V_SIGGEN_FREQ,
        CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        CONST_PSBSMP.V_SIGGEN_OFFSET,
        CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        CONST_PSBSMP.V_WFMREF_SELECTED,
        CONST_PSBSMP.V_WFMREF_SYNC_MODE,
        CONST_PSBSMP.V_WFMREF_GAIN,
        CONST_PSBSMP.V_WFMREF_OFFSET,
        CONST_PSBSMP.V_WFMREF0_START,
        CONST_PSBSMP.V_WFMREF0_END,
        CONST_PSBSMP.V_WFMREF0_IDX,
        CONST_PSBSMP.V_WFMREF1_START,
        CONST_PSBSMP.V_WFMREF1_END,
        CONST_PSBSMP.V_WFMREF1_IDX,
        # --- FBP variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_I_LOAD,
        CONST_PSBSMP.V_V_LOAD,
        CONST_PSBSMP.V_V_DCLINK,
        CONST_PSBSMP.V_TEMP_SWITCHES,)
    groups[_PRUCParms.MIRROR] = (
        # --- mirror variables ---
        CONST_PSBSMP.V_PS_STATUS_1,
        CONST_PSBSMP.V_PS_STATUS_2,
        CONST_PSBSMP.V_PS_STATUS_3,
        CONST_PSBSMP.V_PS_STATUS_4,
        CONST_PSBSMP.V_PS_SETPOINT_1,
        CONST_PSBSMP.V_PS_SETPOINT_2,
        CONST_PSBSMP.V_PS_SETPOINT_3,
        CONST_PSBSMP.V_PS_SETPOINT_4,
        CONST_PSBSMP.V_PS_REFERENCE_1,
        CONST_PSBSMP.V_PS_REFERENCE_2,
        CONST_PSBSMP.V_PS_REFERENCE_3,
        CONST_PSBSMP.V_PS_REFERENCE_4,
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS_1,
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS_2,
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS_3,
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS_4,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS_1,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS_2,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS_3,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS_4,
        CONST_PSBSMP.V_I_LOAD_1,
        CONST_PSBSMP.V_I_LOAD_2,
        CONST_PSBSMP.V_I_LOAD_3,
        CONST_PSBSMP.V_I_LOAD_4,)


class PRUCParmsFBP_DCLink(_PRUCParms):
    """FBP_DCLink-specific PRUC parameters."""

    FREQ_RAMP = 2.0  # [Hz]
    FREQ_SCAN = 2.0  # [Hz]

    # PS model parms
    model = _PSModelFactory.create('FBP_DCLink')
    CONST_PSBSMP = model.bsmp_constants
    Entities = model.entities

    groups = dict()
    # reserved variable groups (not to be used)
    groups[_PRUCParms.ALL] = tuple(sorted(Entities.list_variables(0)))
    groups[_PRUCParms.READONLY] = tuple(sorted(Entities.list_variables(1)))
    groups[_PRUCParms.WRITEABLE] = tuple(sorted(Entities.list_variables(2)))
    # new variable groups useful for PRUController.
    groups[_PRUCParms.ALLRELEVANT] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_FIRMWARE_VERSION,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        # CONST_PSBSMP.V_SIGGEN_ENABLE,
        # CONST_PSBSMP.V_SIGGEN_TYPE,
        # CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        # CONST_PSBSMP.V_SIGGEN_N,
        # CONST_PSBSMP.V_SIGGEN_FREQ,
        # CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        # CONST_PSBSMP.V_SIGGEN_OFFSET,
        # CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        # --- FBP_DCLink variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_MODULES_STATUS,
        CONST_PSBSMP.V_V_OUT,
        CONST_PSBSMP.V_V_OUT_1,
        CONST_PSBSMP.V_V_OUT_2,
        CONST_PSBSMP.V_V_OUT_3,
        CONST_PSBSMP.V_DIG_POT_TAP,)
    groups[_PRUCParms.SYNCOFF] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        # CONST_PSBSMP.V_SIGGEN_ENABLE,
        # CONST_PSBSMP.V_SIGGEN_TYPE,
        # CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        # CONST_PSBSMP.V_SIGGEN_N,
        # CONST_PSBSMP.V_SIGGEN_FREQ,
        # CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        # CONST_PSBSMP.V_SIGGEN_OFFSET,
        # CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        # --- FBP_DCLink variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_MODULES_STATUS,
        CONST_PSBSMP.V_V_OUT,
        CONST_PSBSMP.V_V_OUT_1,
        CONST_PSBSMP.V_V_OUT_2,
        CONST_PSBSMP.V_V_OUT_3,
        CONST_PSBSMP.V_DIG_POT_TAP,)
    groups[_PRUCParms.MIRROR] = groups[_PRUCParms.SYNCOFF]


class PRUCParmsFAC_2S_DCDC(_PRUCParms):
    """FAC_2S specific PRUC parameters.

    Represent FAC_2S_DCDC psmodels.
    """

    FREQ_RAMP = 2.0  # [Hz]
    FREQ_SCAN = 10.0  # [Hz]

    # PS model parms
    model = _PSModelFactory.create('FAC_2S_DCDC')
    CONST_PSBSMP = model.bsmp_constants
    Entities = model.entities

    groups = dict()
    # reserved variable groups (not to be used)
    groups[_PRUCParms.ALL] = tuple(sorted(Entities.list_variables(0)))
    groups[_PRUCParms.READONLY] = tuple(sorted(Entities.list_variables(1)))
    groups[_PRUCParms.WRITEABLE] = tuple(sorted(Entities.list_variables(2)))
    # new variable groups useful for PRUController.
    groups[_PRUCParms.ALLRELEVANT] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_FIRMWARE_VERSION,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        CONST_PSBSMP.V_SIGGEN_ENABLE,
        CONST_PSBSMP.V_SIGGEN_TYPE,
        CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        CONST_PSBSMP.V_SIGGEN_N,
        CONST_PSBSMP.V_SIGGEN_FREQ,
        CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        CONST_PSBSMP.V_SIGGEN_OFFSET,
        CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        CONST_PSBSMP.V_WFMREF_SELECTED,
        CONST_PSBSMP.V_WFMREF_SYNC_MODE,
        CONST_PSBSMP.V_WFMREF_GAIN,
        CONST_PSBSMP.V_WFMREF_OFFSET,
        CONST_PSBSMP.V_WFMREF0_START,
        CONST_PSBSMP.V_WFMREF0_END,
        CONST_PSBSMP.V_WFMREF0_IDX,
        CONST_PSBSMP.V_WFMREF1_START,
        CONST_PSBSMP.V_WFMREF1_END,
        CONST_PSBSMP.V_WFMREF1_IDX,
        # --- FAC_2S_DCDC variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_I_LOAD_MEAN,
        CONST_PSBSMP.V_I_LOAD1,
        CONST_PSBSMP.V_I_LOAD2,
        CONST_PSBSMP.V_V_LOAD,
        CONST_PSBSMP.V_V_OUT_1,
        CONST_PSBSMP.V_V_OUT_2,
        CONST_PSBSMP.V_V_CAPBANK_1,
        CONST_PSBSMP.V_V_CAPBANK_2,
        CONST_PSBSMP.V_DUTY_CYCLE_1,
        CONST_PSBSMP.V_DUTY_CYCLE_2,
        CONST_PSBSMP.V_DUTY_DIFF,
        CONST_PSBSMP.V_I_INPUT_IIB_1,
        CONST_PSBSMP.V_I_OUTPUT_IIB_1,
        CONST_PSBSMP.V_V_INPUT_IIB_1,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_1,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_1,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_1,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_1,
        CONST_PSBSMP.V_I_INPUT_IIB_2,
        CONST_PSBSMP.V_I_OUTPUT_IIB_2,
        CONST_PSBSMP.V_V_INPUT_IIB_2,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_2,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_2,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_2,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_2,
        CONST_PSBSMP.V_IIB_INTERLOCKS_1,
        CONST_PSBSMP.V_IIB_INTERLOCKS_2)
    groups[_PRUCParms.SYNCOFF] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_FIRMWARE_VERSION,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        CONST_PSBSMP.V_SIGGEN_ENABLE,
        CONST_PSBSMP.V_SIGGEN_TYPE,
        CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        CONST_PSBSMP.V_SIGGEN_N,
        CONST_PSBSMP.V_SIGGEN_FREQ,
        CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        CONST_PSBSMP.V_SIGGEN_OFFSET,
        CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        CONST_PSBSMP.V_WFMREF_SELECTED,
        CONST_PSBSMP.V_WFMREF_SYNC_MODE,
        CONST_PSBSMP.V_WFMREF_GAIN,
        CONST_PSBSMP.V_WFMREF_OFFSET,
        CONST_PSBSMP.V_WFMREF0_START,
        CONST_PSBSMP.V_WFMREF0_END,
        CONST_PSBSMP.V_WFMREF0_IDX,
        CONST_PSBSMP.V_WFMREF1_START,
        CONST_PSBSMP.V_WFMREF1_END,
        CONST_PSBSMP.V_WFMREF1_IDX,
        # --- FAC_2S_DCDC variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_I_LOAD_MEAN,
        CONST_PSBSMP.V_I_LOAD1,
        CONST_PSBSMP.V_I_LOAD2,
        CONST_PSBSMP.V_V_LOAD,
        CONST_PSBSMP.V_V_OUT_1,
        CONST_PSBSMP.V_V_OUT_2,
        CONST_PSBSMP.V_V_CAPBANK_1,
        CONST_PSBSMP.V_V_CAPBANK_2,
        CONST_PSBSMP.V_DUTY_CYCLE_1,
        CONST_PSBSMP.V_DUTY_CYCLE_2,
        CONST_PSBSMP.V_DUTY_DIFF,
        CONST_PSBSMP.V_I_INPUT_IIB_1,
        CONST_PSBSMP.V_I_OUTPUT_IIB_1,
        CONST_PSBSMP.V_V_INPUT_IIB_1,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_1,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_1,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_1,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_1,
        CONST_PSBSMP.V_I_INPUT_IIB_2,
        CONST_PSBSMP.V_I_OUTPUT_IIB_2,
        CONST_PSBSMP.V_V_INPUT_IIB_2,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_2,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_2,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_2,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_2,
        CONST_PSBSMP.V_IIB_INTERLOCKS_1,
        CONST_PSBSMP.V_IIB_INTERLOCKS_2)
    groups[_PRUCParms.MIRROR] = groups[_PRUCParms.SYNCOFF]


class PRUCParmsFAC_2P4S_DCDC(_PRUCParms):
    """FAC-specific PRUC parameters.

    Represent FAC_2P4S psmodels.
    """

    FREQ_RAMP = 2.0  # [Hz]
    FREQ_SCAN = 10.0  # [Hz]

    # PS model parms
    model = _PSModelFactory.create('FAC_2P4S_DCDC')
    CONST_PSBSMP = model.bsmp_constants
    Entities = model.entities

    groups = dict()
    # reserved variable groups (not to be used)
    groups[_PRUCParms.ALL] = tuple(sorted(Entities.list_variables(0)))
    groups[_PRUCParms.READONLY] = tuple(sorted(Entities.list_variables(1)))
    groups[_PRUCParms.WRITEABLE] = tuple(sorted(Entities.list_variables(2)))
    # new variable groups useful for PRUController.
    groups[_PRUCParms.ALLRELEVANT] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_FIRMWARE_VERSION,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        CONST_PSBSMP.V_SIGGEN_ENABLE,
        CONST_PSBSMP.V_SIGGEN_TYPE,
        CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        CONST_PSBSMP.V_SIGGEN_N,
        CONST_PSBSMP.V_SIGGEN_FREQ,
        CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        CONST_PSBSMP.V_SIGGEN_OFFSET,
        CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        CONST_PSBSMP.V_WFMREF_SELECTED,
        CONST_PSBSMP.V_WFMREF_SYNC_MODE,
        CONST_PSBSMP.V_WFMREF_GAIN,
        CONST_PSBSMP.V_WFMREF_OFFSET,
        CONST_PSBSMP.V_WFMREF0_START,
        CONST_PSBSMP.V_WFMREF0_END,
        CONST_PSBSMP.V_WFMREF0_IDX,
        CONST_PSBSMP.V_WFMREF1_START,
        CONST_PSBSMP.V_WFMREF1_END,
        CONST_PSBSMP.V_WFMREF1_IDX,
        # --- FAC variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_I_LOAD_MEAN,
        CONST_PSBSMP.V_I_LOAD1,
        CONST_PSBSMP.V_I_LOAD2,
        CONST_PSBSMP.V_I_ARM_1,
        CONST_PSBSMP.V_I_ARM_2,
        CONST_PSBSMP.V_V_LOAD,
        CONST_PSBSMP.V_V_CAPBANK_1,
        CONST_PSBSMP.V_V_CAPBANK_2,
        CONST_PSBSMP.V_V_CAPBANK_3,
        CONST_PSBSMP.V_V_CAPBANK_4,
        CONST_PSBSMP.V_V_CAPBANK_5,
        CONST_PSBSMP.V_V_CAPBANK_6,
        CONST_PSBSMP.V_V_CAPBANK_7,
        CONST_PSBSMP.V_V_CAPBANK_8,
        CONST_PSBSMP.V_V_OUT_1,
        CONST_PSBSMP.V_V_OUT_2,
        CONST_PSBSMP.V_V_OUT_3,
        CONST_PSBSMP.V_V_OUT_4,
        CONST_PSBSMP.V_V_OUT_5,
        CONST_PSBSMP.V_V_OUT_6,
        CONST_PSBSMP.V_V_OUT_7,
        CONST_PSBSMP.V_V_OUT_8,
        CONST_PSBSMP.V_DUTY_CYCLE_1,
        CONST_PSBSMP.V_DUTY_CYCLE_2,
        CONST_PSBSMP.V_DUTY_CYCLE_3,
        CONST_PSBSMP.V_DUTY_CYCLE_4,
        CONST_PSBSMP.V_DUTY_CYCLE_5,
        CONST_PSBSMP.V_DUTY_CYCLE_6,
        CONST_PSBSMP.V_DUTY_CYCLE_7,
        CONST_PSBSMP.V_DUTY_CYCLE_8,
        CONST_PSBSMP.V_I_INPUT_IIB_1,
        CONST_PSBSMP.V_I_OUTPUT_IIB_1,
        CONST_PSBSMP.V_V_INPUT_IIB_1,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_1,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_1,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_1,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_1,
        CONST_PSBSMP.V_I_INPUT_IIB_2,
        CONST_PSBSMP.V_I_OUTPUT_IIB_2,
        CONST_PSBSMP.V_V_INPUT_IIB_2,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_2,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_2,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_2,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_2,
        CONST_PSBSMP.V_I_INPUT_IIB_3,
        CONST_PSBSMP.V_I_OUTPUT_IIB_3,
        CONST_PSBSMP.V_V_INPUT_IIB_3,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_3,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_3,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_3,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_3,
        CONST_PSBSMP.V_I_INPUT_IIB_4,
        CONST_PSBSMP.V_I_OUTPUT_IIB_4,
        CONST_PSBSMP.V_V_INPUT_IIB_4,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_4,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_4,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_4,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_4,
        CONST_PSBSMP.V_I_INPUT_IIB_5,
        CONST_PSBSMP.V_I_OUTPUT_IIB_5,
        CONST_PSBSMP.V_V_INPUT_IIB_5,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_5,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_5,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_5,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_5,
        CONST_PSBSMP.V_I_INPUT_IIB_6,
        CONST_PSBSMP.V_I_OUTPUT_IIB_6,
        CONST_PSBSMP.V_V_INPUT_IIB_6,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_6,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_6,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_6,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_6,
        CONST_PSBSMP.V_I_INPUT_IIB_7,
        CONST_PSBSMP.V_I_OUTPUT_IIB_7,
        CONST_PSBSMP.V_V_INPUT_IIB_7,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_7,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_7,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_7,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_7,
        CONST_PSBSMP.V_I_INPUT_IIB_8,
        CONST_PSBSMP.V_I_OUTPUT_IIB_8,
        CONST_PSBSMP.V_V_INPUT_IIB_8,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_8,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_8,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_8,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_8,
        CONST_PSBSMP.V_IIB_INTERLOCKS_1,
        CONST_PSBSMP.V_IIB_INTERLOCKS_2,
        CONST_PSBSMP.V_IIB_INTERLOCKS_3,
        CONST_PSBSMP.V_IIB_INTERLOCKS_4,
        CONST_PSBSMP.V_IIB_INTERLOCKS_5,
        CONST_PSBSMP.V_IIB_INTERLOCKS_6,
        CONST_PSBSMP.V_IIB_INTERLOCKS_7,
        CONST_PSBSMP.V_IIB_INTERLOCKS_8,)
    groups[_PRUCParms.SYNCOFF] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        CONST_PSBSMP.V_SIGGEN_ENABLE,
        CONST_PSBSMP.V_SIGGEN_TYPE,
        CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        CONST_PSBSMP.V_SIGGEN_N,
        CONST_PSBSMP.V_SIGGEN_FREQ,
        CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        CONST_PSBSMP.V_SIGGEN_OFFSET,
        CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        CONST_PSBSMP.V_WFMREF_SELECTED,
        CONST_PSBSMP.V_WFMREF_SYNC_MODE,
        CONST_PSBSMP.V_WFMREF_GAIN,
        CONST_PSBSMP.V_WFMREF_OFFSET,
        CONST_PSBSMP.V_WFMREF0_START,
        CONST_PSBSMP.V_WFMREF0_END,
        CONST_PSBSMP.V_WFMREF0_IDX,
        CONST_PSBSMP.V_WFMREF1_START,
        CONST_PSBSMP.V_WFMREF1_END,
        CONST_PSBSMP.V_WFMREF1_IDX,
        # --- FAC variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_I_LOAD_MEAN,
        CONST_PSBSMP.V_I_LOAD1,
        CONST_PSBSMP.V_I_LOAD2,
        CONST_PSBSMP.V_I_ARM_1,
        CONST_PSBSMP.V_I_ARM_2,
        CONST_PSBSMP.V_V_LOAD,
        CONST_PSBSMP.V_V_CAPBANK_1,
        CONST_PSBSMP.V_V_CAPBANK_2,
        CONST_PSBSMP.V_V_CAPBANK_3,
        CONST_PSBSMP.V_V_CAPBANK_4,
        CONST_PSBSMP.V_V_CAPBANK_5,
        CONST_PSBSMP.V_V_CAPBANK_6,
        CONST_PSBSMP.V_V_CAPBANK_7,
        CONST_PSBSMP.V_V_CAPBANK_8,
        CONST_PSBSMP.V_V_OUT_1,
        CONST_PSBSMP.V_V_OUT_2,
        CONST_PSBSMP.V_V_OUT_3,
        CONST_PSBSMP.V_V_OUT_4,
        CONST_PSBSMP.V_V_OUT_5,
        CONST_PSBSMP.V_V_OUT_6,
        CONST_PSBSMP.V_V_OUT_7,
        CONST_PSBSMP.V_V_OUT_8,
        CONST_PSBSMP.V_DUTY_CYCLE_1,
        CONST_PSBSMP.V_DUTY_CYCLE_2,
        CONST_PSBSMP.V_DUTY_CYCLE_3,
        CONST_PSBSMP.V_DUTY_CYCLE_4,
        CONST_PSBSMP.V_DUTY_CYCLE_5,
        CONST_PSBSMP.V_DUTY_CYCLE_6,
        CONST_PSBSMP.V_DUTY_CYCLE_7,
        CONST_PSBSMP.V_DUTY_CYCLE_8,
        CONST_PSBSMP.V_I_INPUT_IIB_1,
        CONST_PSBSMP.V_I_OUTPUT_IIB_1,
        CONST_PSBSMP.V_V_INPUT_IIB_1,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_1,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_1,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_1,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_1,
        CONST_PSBSMP.V_I_INPUT_IIB_2,
        CONST_PSBSMP.V_I_OUTPUT_IIB_2,
        CONST_PSBSMP.V_V_INPUT_IIB_2,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_2,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_2,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_2,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_2,
        CONST_PSBSMP.V_I_INPUT_IIB_3,
        CONST_PSBSMP.V_I_OUTPUT_IIB_3,
        CONST_PSBSMP.V_V_INPUT_IIB_3,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_3,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_3,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_3,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_3,
        CONST_PSBSMP.V_I_INPUT_IIB_4,
        CONST_PSBSMP.V_I_OUTPUT_IIB_4,
        CONST_PSBSMP.V_V_INPUT_IIB_4,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_4,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_4,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_4,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_4,
        CONST_PSBSMP.V_I_INPUT_IIB_5,
        CONST_PSBSMP.V_I_OUTPUT_IIB_5,
        CONST_PSBSMP.V_V_INPUT_IIB_5,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_5,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_5,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_5,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_5,
        CONST_PSBSMP.V_I_INPUT_IIB_6,
        CONST_PSBSMP.V_I_OUTPUT_IIB_6,
        CONST_PSBSMP.V_V_INPUT_IIB_6,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_6,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_6,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_6,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_6,
        CONST_PSBSMP.V_I_INPUT_IIB_7,
        CONST_PSBSMP.V_I_OUTPUT_IIB_7,
        CONST_PSBSMP.V_V_INPUT_IIB_7,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_7,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_7,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_7,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_7,
        CONST_PSBSMP.V_I_INPUT_IIB_8,
        CONST_PSBSMP.V_I_OUTPUT_IIB_8,
        CONST_PSBSMP.V_V_INPUT_IIB_8,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_8,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_8,
        CONST_PSBSMP.V_DRIVER_ERROR_1_IIB_8,
        CONST_PSBSMP.V_DRIVER_ERROR_2_IIB_8,
        CONST_PSBSMP.V_IIB_INTERLOCKS_1,
        CONST_PSBSMP.V_IIB_INTERLOCKS_2,
        CONST_PSBSMP.V_IIB_INTERLOCKS_3,
        CONST_PSBSMP.V_IIB_INTERLOCKS_4,
        CONST_PSBSMP.V_IIB_INTERLOCKS_5,
        CONST_PSBSMP.V_IIB_INTERLOCKS_6,
        CONST_PSBSMP.V_IIB_INTERLOCKS_7,
        CONST_PSBSMP.V_IIB_INTERLOCKS_8,)
    groups[_PRUCParms.MIRROR] = groups[_PRUCParms.SYNCOFF]


class PRUCParmsFAC_DCDC(_PRUCParms):
    """FAC-specific PRUC parameters.

    Represent FAC, FAC_2S, FAC_2P4S psmodels.
    """

    FREQ_RAMP = 2.0  # [Hz]
    FREQ_SCAN = 10.0  # [Hz]

    # PS model parms
    model = _PSModelFactory.create('FAC_DCDC')
    CONST_PSBSMP = model.bsmp_constants
    Entities = model.entities

    groups = dict()
    # reserved variable groups (not to be used)
    groups[_PRUCParms.ALL] = tuple(sorted(Entities.list_variables(0)))
    groups[_PRUCParms.READONLY] = tuple(sorted(Entities.list_variables(1)))
    groups[_PRUCParms.WRITEABLE] = tuple(sorted(Entities.list_variables(2)))
    # new variable groups useful for PRUController.
    groups[_PRUCParms.ALLRELEVANT] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_FIRMWARE_VERSION,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        CONST_PSBSMP.V_SIGGEN_ENABLE,
        CONST_PSBSMP.V_SIGGEN_TYPE,
        CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        CONST_PSBSMP.V_SIGGEN_N,
        CONST_PSBSMP.V_SIGGEN_FREQ,
        CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        CONST_PSBSMP.V_SIGGEN_OFFSET,
        CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        CONST_PSBSMP.V_WFMREF_SELECTED,
        CONST_PSBSMP.V_WFMREF_SYNC_MODE,
        CONST_PSBSMP.V_WFMREF_GAIN,
        CONST_PSBSMP.V_WFMREF_OFFSET,
        CONST_PSBSMP.V_WFMREF0_START,
        CONST_PSBSMP.V_WFMREF0_END,
        CONST_PSBSMP.V_WFMREF0_IDX,
        CONST_PSBSMP.V_WFMREF1_START,
        CONST_PSBSMP.V_WFMREF1_END,
        CONST_PSBSMP.V_WFMREF1_IDX,
        # --- FAC variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_I_LOAD_MEAN,
        CONST_PSBSMP.V_I_LOAD1,
        CONST_PSBSMP.V_I_LOAD2,
        CONST_PSBSMP.V_V_LOAD,
        CONST_PSBSMP.V_V_CAPBANK,
        CONST_PSBSMP.V_TEMP_INDUCTORS,
        CONST_PSBSMP.V_TEMP_IGBTS,
        CONST_PSBSMP.V_DUTY_CYCLE,)
    groups[_PRUCParms.SYNCOFF] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        CONST_PSBSMP.V_SIGGEN_ENABLE,
        CONST_PSBSMP.V_SIGGEN_TYPE,
        CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        CONST_PSBSMP.V_SIGGEN_N,
        CONST_PSBSMP.V_SIGGEN_FREQ,
        CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        CONST_PSBSMP.V_SIGGEN_OFFSET,
        CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        CONST_PSBSMP.V_WFMREF_SELECTED,
        CONST_PSBSMP.V_WFMREF_SYNC_MODE,
        CONST_PSBSMP.V_WFMREF_GAIN,
        CONST_PSBSMP.V_WFMREF_OFFSET,
        CONST_PSBSMP.V_WFMREF0_START,
        CONST_PSBSMP.V_WFMREF0_END,
        CONST_PSBSMP.V_WFMREF0_IDX,
        CONST_PSBSMP.V_WFMREF1_START,
        CONST_PSBSMP.V_WFMREF1_END,
        CONST_PSBSMP.V_WFMREF1_IDX,
        # --- FAC variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_I_LOAD_MEAN,
        CONST_PSBSMP.V_I_LOAD1,
        CONST_PSBSMP.V_I_LOAD2,
        CONST_PSBSMP.V_V_LOAD,
        CONST_PSBSMP.V_V_CAPBANK,
        CONST_PSBSMP.V_TEMP_INDUCTORS,
        CONST_PSBSMP.V_TEMP_IGBTS,
        CONST_PSBSMP.V_DUTY_CYCLE,)
    groups[_PRUCParms.MIRROR] = groups[_PRUCParms.SYNCOFF]


class PRUCParmsFAC_2S_ACDC(_PRUCParms):
    """FAC_2S_ACDC-specific PRUC parameters."""

    FREQ_RAMP = 2.0  # [Hz]
    FREQ_SCAN = 2.0  # [Hz]

    # PS model parms
    model = _PSModelFactory.create('FAC_2S_ACDC')
    CONST_PSBSMP = model.bsmp_constants
    Entities = model.entities

    groups = dict()
    # reserved variable groups (not to be used)
    groups[_PRUCParms.ALL] = tuple(sorted(Entities.list_variables(0)))
    groups[_PRUCParms.READONLY] = tuple(sorted(Entities.list_variables(1)))
    groups[_PRUCParms.WRITEABLE] = tuple(sorted(Entities.list_variables(2)))
    # new variable groups useful for PRUController.
    groups[_PRUCParms.ALLRELEVANT] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_FIRMWARE_VERSION,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        # CONST_PSBSMP.V_SIGGEN_ENABLE,
        # CONST_PSBSMP.V_SIGGEN_TYPE,
        # CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        # CONST_PSBSMP.V_SIGGEN_N,
        # CONST_PSBSMP.V_SIGGEN_FREQ,
        # CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        # CONST_PSBSMP.V_SIGGEN_OFFSET,
        # CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        # CONST_PSBSMP.V_WFMREF_SELECTED,
        # CONST_PSBSMP.V_WFMREF_SYNC_MODE,
        # CONST_PSBSMP.V_WFMREF_GAIN,
        # CONST_PSBSMP.V_WFMREF_OFFSET,
        # CONST_PSBSMP.V_WFMREF0_START,
        # CONST_PSBSMP.V_WFMREF0_END,
        # CONST_PSBSMP.V_WFMREF0_IDX,
        # CONST_PSBSMP.V_WFMREF1_START,
        # CONST_PSBSMP.V_WFMREF1_END,
        # CONST_PSBSMP.V_WFMREF1_IDX,
        # --- FAC_2S_ACDC variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_V_CAPBANK,
        CONST_PSBSMP.V_V_OUT_RECTIFIER,
        CONST_PSBSMP.V_I_OUT_RECTIFIER,
        CONST_PSBSMP.V_TEMP_HEATSINK,
        CONST_PSBSMP.V_TEMP_INDUCTORS,
        CONST_PSBSMP.V_DUTY_CYCLE,)
    groups[_PRUCParms.SYNCOFF] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        # CONST_PSBSMP.V_SIGGEN_ENABLE,
        # CONST_PSBSMP.V_SIGGEN_TYPE,
        # CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        # CONST_PSBSMP.V_SIGGEN_N,
        # CONST_PSBSMP.V_SIGGEN_FREQ,
        # CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        # CONST_PSBSMP.V_SIGGEN_OFFSET,
        # CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        # CONST_PSBSMP.V_WFMREF_SELECTED,
        # CONST_PSBSMP.V_WFMREF_SYNC_MODE,
        # CONST_PSBSMP.V_WFMREF_GAIN,
        # CONST_PSBSMP.V_WFMREF_OFFSET,
        # CONST_PSBSMP.V_WFMREF0_START,
        # CONST_PSBSMP.V_WFMREF0_END,
        # CONST_PSBSMP.V_WFMREF0_IDX,
        # CONST_PSBSMP.V_WFMREF1_START,
        # CONST_PSBSMP.V_WFMREF1_END,
        # CONST_PSBSMP.V_WFMREF1_IDX,
        # --- FAC_2S_ACDC variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_V_CAPBANK,
        CONST_PSBSMP.V_V_OUT_RECTIFIER,
        CONST_PSBSMP.V_I_OUT_RECTIFIER,
        CONST_PSBSMP.V_TEMP_HEATSINK,
        CONST_PSBSMP.V_TEMP_INDUCTORS,
        CONST_PSBSMP.V_DUTY_CYCLE,)
    groups[_PRUCParms.MIRROR] = groups[_PRUCParms.SYNCOFF]


class PRUCParmsFAC_2P4S_ACDC(_PRUCParms):
    """FAC_2P4S_ACDC-specific PRUC parameters."""

    FREQ_RAMP = 2.0  # [Hz]
    FREQ_SCAN = 2.0  # [Hz]

    # PS model parms
    model = _PSModelFactory.create('FAC_2P4S_ACDC')
    CONST_PSBSMP = model.bsmp_constants
    Entities = model.entities

    groups = dict()
    # reserved variable groups (not to be used)
    groups[_PRUCParms.ALL] = tuple(sorted(Entities.list_variables(0)))
    groups[_PRUCParms.READONLY] = tuple(sorted(Entities.list_variables(1)))
    groups[_PRUCParms.WRITEABLE] = tuple(sorted(Entities.list_variables(2)))
    # new variable groups usefull for PRUController.
    groups[_PRUCParms.ALLRELEVANT] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_FIRMWARE_VERSION,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        # CONST_PSBSMP.V_SIGGEN_ENABLE,
        # CONST_PSBSMP.V_SIGGEN_TYPE,
        # CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        # CONST_PSBSMP.V_SIGGEN_N,
        # CONST_PSBSMP.V_SIGGEN_FREQ,
        # CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        # CONST_PSBSMP.V_SIGGEN_OFFSET,
        # CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        # --- FAC_2P4S_ACDC variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_V_CAPACITOR_BANK,
        CONST_PSBSMP.V_V_OUT_RECTIFIER,
        CONST_PSBSMP.V_I_OUT_RECTIFIER,
        CONST_PSBSMP.V_TEMP_HEATSINK,
        CONST_PSBSMP.V_TEMP_INDUCTORS,
        CONST_PSBSMP.V_DUTY_CYCLE,
        CONST_PSBSMP.V_I_INPUT_IS_IIB,
        CONST_PSBSMP.V_V_INPUT_IS_IIB,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IS_IIB,
        CONST_PSBSMP.V_TEMP_HEATSINK_IS_IIB,
        CONST_PSBSMP.V_V_OUTPUT_CMD_IIB,
        CONST_PSBSMP.V_V_CAPBANK_CMD_IIB,
        CONST_PSBSMP.V_TEMP_INDUCTOR_CMD_IIB,
        CONST_PSBSMP.V_TEMP_HEATSINK_CMD_IIB,
        CONST_PSBSMP.V_I_LEAKAGE_CMD_IIB,
        CONST_PSBSMP.V_IIB_INTERLOCKS_IS,
        CONST_PSBSMP.V_IIB_INTERLOCKS_CMD,)
    groups[_PRUCParms.SYNCOFF] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        # CONST_PSBSMP.V_SIGGEN_ENABLE,
        # CONST_PSBSMP.V_SIGGEN_TYPE,
        # CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        # CONST_PSBSMP.V_SIGGEN_N,
        # CONST_PSBSMP.V_SIGGEN_FREQ,
        # CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        # CONST_PSBSMP.V_SIGGEN_OFFSET,
        # CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        # --- FAC_2P4S_ACDC variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_V_CAPACITOR_BANK,
        CONST_PSBSMP.V_V_OUT_RECTIFIER,
        CONST_PSBSMP.V_I_OUT_RECTIFIER,
        CONST_PSBSMP.V_TEMP_HEATSINK,
        CONST_PSBSMP.V_TEMP_INDUCTORS,
        CONST_PSBSMP.V_DUTY_CYCLE,
        CONST_PSBSMP.V_I_INPUT_IS_IIB,
        CONST_PSBSMP.V_V_INPUT_IS_IIB,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IS_IIB,
        CONST_PSBSMP.V_TEMP_HEATSINK_IS_IIB,
        CONST_PSBSMP.V_V_OUTPUT_CMD_IIB,
        CONST_PSBSMP.V_V_CAPBANK_CMD_IIB,
        CONST_PSBSMP.V_TEMP_INDUCTOR_CMD_IIB,
        CONST_PSBSMP.V_TEMP_HEATSINK_CMD_IIB,
        CONST_PSBSMP.V_I_LEAKAGE_CMD_IIB,
        CONST_PSBSMP.V_IIB_INTERLOCKS_IS,
        CONST_PSBSMP.V_IIB_INTERLOCKS_CMD,)
    groups[_PRUCParms.MIRROR] = groups[_PRUCParms.SYNCOFF]


class PRUCParmsFAP(_PRUCParms):
    """FAC-specific PRUC parameters.

    Represent FAP
    """

    FREQ_RAMP = 2.0  # [Hz]
    FREQ_SCAN = 10.0  # [Hz]

    # PS model parms
    model = _PSModelFactory.create('FAP')
    CONST_PSBSMP = model.bsmp_constants
    Entities = model.entities

    groups = dict()
    # reserved variable groups (not to be used)
    groups[_PRUCParms.ALL] = tuple(sorted(Entities.list_variables(0)))
    groups[_PRUCParms.READONLY] = tuple(sorted(Entities.list_variables(1)))
    groups[_PRUCParms.WRITEABLE] = tuple(sorted(Entities.list_variables(2)))
    # new variable groups useful for PRUController.
    groups[_PRUCParms.ALLRELEVANT] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_FIRMWARE_VERSION,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        CONST_PSBSMP.V_SIGGEN_ENABLE,
        CONST_PSBSMP.V_SIGGEN_TYPE,
        CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        CONST_PSBSMP.V_SIGGEN_N,
        CONST_PSBSMP.V_SIGGEN_FREQ,
        CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        CONST_PSBSMP.V_SIGGEN_OFFSET,
        CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        CONST_PSBSMP.V_WFMREF_SELECTED,
        CONST_PSBSMP.V_WFMREF_SYNC_MODE,
        CONST_PSBSMP.V_WFMREF_GAIN,
        CONST_PSBSMP.V_WFMREF_OFFSET,
        CONST_PSBSMP.V_WFMREF0_START,
        CONST_PSBSMP.V_WFMREF0_END,
        CONST_PSBSMP.V_WFMREF0_IDX,
        CONST_PSBSMP.V_WFMREF1_START,
        CONST_PSBSMP.V_WFMREF1_END,
        CONST_PSBSMP.V_WFMREF1_IDX,
        # --- FAP variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_I_LOAD_MEAN,
        CONST_PSBSMP.V_I_LOAD1,
        CONST_PSBSMP.V_I_LOAD2,
        CONST_PSBSMP.V_V_DCLINK,
        CONST_PSBSMP.V_I_IGBT_1,
        CONST_PSBSMP.V_I_IGBT_2,
        CONST_PSBSMP.V_DUTY_CYCLE_1,
        CONST_PSBSMP.V_DUTY_CYCLE_2,
        CONST_PSBSMP.V_DUTY_DIFF,
        CONST_PSBSMP.V_V_INPUT_IIB,
        CONST_PSBSMP.V_V_OUTPUT_IIB,
        CONST_PSBSMP.V_I_IGBT_1_IIB,
        CONST_PSBSMP.V_I_IGBT_2_IIB,
        CONST_PSBSMP.V_TEMP_IGBT_1_IIB,
        CONST_PSBSMP.V_TEMP_IGBT_2_IIB,
        CONST_PSBSMP.V_V_DRIVER_IIB,
        CONST_PSBSMP.V_I_DRIVER_1_IIB,
        CONST_PSBSMP.V_I_DRIVER_2_IIB,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB,
        CONST_PSBSMP.V_IIB_INTERLOCKS,)
    groups[_PRUCParms.SYNCOFF] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        CONST_PSBSMP.V_SIGGEN_ENABLE,
        CONST_PSBSMP.V_SIGGEN_TYPE,
        CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        CONST_PSBSMP.V_SIGGEN_N,
        CONST_PSBSMP.V_SIGGEN_FREQ,
        CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        CONST_PSBSMP.V_SIGGEN_OFFSET,
        CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        CONST_PSBSMP.V_WFMREF_SELECTED,
        CONST_PSBSMP.V_WFMREF_SYNC_MODE,
        CONST_PSBSMP.V_WFMREF_GAIN,
        CONST_PSBSMP.V_WFMREF_OFFSET,
        CONST_PSBSMP.V_WFMREF0_START,
        CONST_PSBSMP.V_WFMREF0_END,
        CONST_PSBSMP.V_WFMREF0_IDX,
        CONST_PSBSMP.V_WFMREF1_START,
        CONST_PSBSMP.V_WFMREF1_END,
        CONST_PSBSMP.V_WFMREF1_IDX,
        # --- FAP variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_I_LOAD_MEAN,
        CONST_PSBSMP.V_I_LOAD1,
        CONST_PSBSMP.V_I_LOAD2,
        CONST_PSBSMP.V_V_DCLINK,
        CONST_PSBSMP.V_I_IGBT_1,
        CONST_PSBSMP.V_I_IGBT_2,
        CONST_PSBSMP.V_DUTY_CYCLE_1,
        CONST_PSBSMP.V_DUTY_CYCLE_2,
        CONST_PSBSMP.V_DUTY_DIFF,
        CONST_PSBSMP.V_V_INPUT_IIB,
        CONST_PSBSMP.V_V_OUTPUT_IIB,
        CONST_PSBSMP.V_I_IGBT_1_IIB,
        CONST_PSBSMP.V_I_IGBT_2_IIB,
        CONST_PSBSMP.V_TEMP_IGBT_1_IIB,
        CONST_PSBSMP.V_TEMP_IGBT_2_IIB,
        CONST_PSBSMP.V_V_DRIVER_IIB,
        CONST_PSBSMP.V_I_DRIVER_1_IIB,
        CONST_PSBSMP.V_I_DRIVER_2_IIB,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB,
        CONST_PSBSMP.V_IIB_INTERLOCKS,)
    groups[_PRUCParms.MIRROR] = groups[_PRUCParms.SYNCOFF]


class PRUCParmsFAP_4P(_PRUCParms):
    """FAC-specific PRUC parameters.

    Represent FAP_4P
    """

    FREQ_RAMP = 2.0  # [Hz]
    FREQ_SCAN = 10.0  # [Hz]

    # PS model parms
    model = _PSModelFactory.create('FAP_4P')
    CONST_PSBSMP = model.bsmp_constants
    Entities = model.entities

    groups = dict()
    # reserved variable groups (not to be used)
    groups[_PRUCParms.ALL] = tuple(sorted(Entities.list_variables(0)))
    groups[_PRUCParms.READONLY] = tuple(sorted(Entities.list_variables(1)))
    groups[_PRUCParms.WRITEABLE] = tuple(sorted(Entities.list_variables(2)))
    # new variable groups useful for PRUController.
    groups[_PRUCParms.ALLRELEVANT] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_FIRMWARE_VERSION,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        CONST_PSBSMP.V_SIGGEN_ENABLE,
        CONST_PSBSMP.V_SIGGEN_TYPE,
        CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        CONST_PSBSMP.V_SIGGEN_N,
        CONST_PSBSMP.V_SIGGEN_FREQ,
        CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        CONST_PSBSMP.V_SIGGEN_OFFSET,
        CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        CONST_PSBSMP.V_WFMREF_SELECTED,
        CONST_PSBSMP.V_WFMREF_SYNC_MODE,
        CONST_PSBSMP.V_WFMREF_GAIN,
        CONST_PSBSMP.V_WFMREF_OFFSET,
        CONST_PSBSMP.V_WFMREF0_START,
        CONST_PSBSMP.V_WFMREF0_END,
        CONST_PSBSMP.V_WFMREF0_IDX,
        CONST_PSBSMP.V_WFMREF1_START,
        CONST_PSBSMP.V_WFMREF1_END,
        CONST_PSBSMP.V_WFMREF1_IDX,
        # --- FAP variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_I_LOAD_MEAN,
        CONST_PSBSMP.V_I_LOAD1,
        CONST_PSBSMP.V_I_LOAD2,
        CONST_PSBSMP.V_V_DCLINK,
        CONST_PSBSMP.V_I_IGBT_1,
        CONST_PSBSMP.V_I_IGBT_2,
        CONST_PSBSMP.V_DUTY_CYCLE_1,
        CONST_PSBSMP.V_DUTY_CYCLE_2,
        CONST_PSBSMP.V_DUTY_DIFF,
        CONST_PSBSMP.V_V_INPUT_IIB,
        CONST_PSBSMP.V_V_OUTPUT_IIB,
        CONST_PSBSMP.V_I_IGBT_1_IIB,
        CONST_PSBSMP.V_I_IGBT_2_IIB,
        CONST_PSBSMP.V_TEMP_IGBT_1_IIB,
        CONST_PSBSMP.V_TEMP_IGBT_2_IIB,
        CONST_PSBSMP.V_V_DRIVER_IIB,
        CONST_PSBSMP.V_I_DRIVER_1_IIB,
        CONST_PSBSMP.V_I_DRIVER_2_IIB,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB,
        CONST_PSBSMP.V_IIB_INTERLOCKS,)
    groups[_PRUCParms.SYNCOFF] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        CONST_PSBSMP.V_SIGGEN_ENABLE,
        CONST_PSBSMP.V_SIGGEN_TYPE,
        CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        CONST_PSBSMP.V_SIGGEN_N,
        CONST_PSBSMP.V_SIGGEN_FREQ,
        CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        CONST_PSBSMP.V_SIGGEN_OFFSET,
        CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        # --- FAP variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_I_LOAD_MEAN,
        CONST_PSBSMP.V_I_LOAD1,
        CONST_PSBSMP.V_I_LOAD2,
        CONST_PSBSMP.V_V_DCLINK,
        CONST_PSBSMP.V_I_IGBT_1,
        CONST_PSBSMP.V_I_IGBT_2,
        CONST_PSBSMP.V_DUTY_CYCLE_1,
        CONST_PSBSMP.V_DUTY_CYCLE_2,
        CONST_PSBSMP.V_DUTY_DIFF,
        CONST_PSBSMP.V_V_INPUT_IIB,
        CONST_PSBSMP.V_V_OUTPUT_IIB,
        CONST_PSBSMP.V_I_IGBT_1_IIB,
        CONST_PSBSMP.V_I_IGBT_2_IIB,
        CONST_PSBSMP.V_TEMP_IGBT_1_IIB,
        CONST_PSBSMP.V_TEMP_IGBT_2_IIB,
        CONST_PSBSMP.V_V_DRIVER_IIB,
        CONST_PSBSMP.V_I_DRIVER_1_IIB,
        CONST_PSBSMP.V_I_DRIVER_2_IIB,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB,
        CONST_PSBSMP.V_IIB_INTERLOCKS,)
    groups[_PRUCParms.MIRROR] = groups[_PRUCParms.SYNCOFF]


class PRUCParmsFAP_2P2S(_PRUCParms):
    """FAC_2P2S-specific PRUC parameters.

    Represent FAP_2P2S
    """

    FREQ_RAMP = 2.0  # [Hz]
    FREQ_SCAN = 10.0  # [Hz]

    # PS model parms
    model = _PSModelFactory.create('FAP_2P2S')
    CONST_PSBSMP = model.bsmp_constants
    Entities = model.entities

    groups = dict()
    # reserved variable groups (not to be used)
    groups[_PRUCParms.ALL] = tuple(sorted(Entities.list_variables(0)))
    groups[_PRUCParms.READONLY] = tuple(sorted(Entities.list_variables(1)))
    groups[_PRUCParms.WRITEABLE] = tuple(sorted(Entities.list_variables(2)))
    # new variable groups usefull for PRUController.
    groups[_PRUCParms.ALLRELEVANT] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_FIRMWARE_VERSION,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        CONST_PSBSMP.V_SIGGEN_ENABLE,
        CONST_PSBSMP.V_SIGGEN_TYPE,
        CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        CONST_PSBSMP.V_SIGGEN_N,
        CONST_PSBSMP.V_SIGGEN_FREQ,
        CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        CONST_PSBSMP.V_SIGGEN_OFFSET,
        CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        CONST_PSBSMP.V_WFMREF_SELECTED,
        CONST_PSBSMP.V_WFMREF_SYNC_MODE,
        CONST_PSBSMP.V_WFMREF_GAIN,
        CONST_PSBSMP.V_WFMREF_OFFSET,
        CONST_PSBSMP.V_WFMREF0_START,
        CONST_PSBSMP.V_WFMREF0_END,
        CONST_PSBSMP.V_WFMREF0_IDX,
        CONST_PSBSMP.V_WFMREF1_START,
        CONST_PSBSMP.V_WFMREF1_END,
        CONST_PSBSMP.V_WFMREF1_IDX,
        # --- FAP_2P2S variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_I_LOAD_MEAN,
        CONST_PSBSMP.V_I_LOAD1,
        CONST_PSBSMP.V_I_LOAD2,
        CONST_PSBSMP.V_I_ARM_1,
        CONST_PSBSMP.V_I_ARM_2,
        CONST_PSBSMP.V_I_IGBT_1_1,
        CONST_PSBSMP.V_I_IGBT_2_1,
        CONST_PSBSMP.V_I_IGBT_1_2,
        CONST_PSBSMP.V_I_IGBT_2_2,
        CONST_PSBSMP.V_I_IGBT_1_3,
        CONST_PSBSMP.V_I_IGBT_2_3,
        CONST_PSBSMP.V_I_IGBT_1_4,
        CONST_PSBSMP.V_I_IGBT_2_4,
        CONST_PSBSMP.V_V_DCLINK_1,
        CONST_PSBSMP.V_V_DCLINK_2,
        CONST_PSBSMP.V_V_DCLINK_3,
        CONST_PSBSMP.V_V_DCLINK_4,
        CONST_PSBSMP.V_DUTY_MEAN,
        CONST_PSBSMP.V_DUTY_ARMS_DIFF,
        CONST_PSBSMP.V_DUTY_CYCLE_1_1,
        CONST_PSBSMP.V_DUTY_CYCLE_2_1,
        CONST_PSBSMP.V_DUTY_CYCLE_1_2,
        CONST_PSBSMP.V_DUTY_CYCLE_2_2,
        CONST_PSBSMP.V_DUTY_CYCLE_1_3,
        CONST_PSBSMP.V_DUTY_CYCLE_2_3,
        CONST_PSBSMP.V_DUTY_CYCLE_1_4,
        CONST_PSBSMP.V_DUTY_CYCLE_2_4,
        CONST_PSBSMP.V_V_INPUT_IIB_1,
        CONST_PSBSMP.V_V_OUTPUT_IIB_1,
        CONST_PSBSMP.V_I_IGBT_1_IIB_1,
        CONST_PSBSMP.V_I_IGBT_2_IIB_1,
        CONST_PSBSMP.V_TEMP_IGBT_1_IIB_1,
        CONST_PSBSMP.V_TEMP_IGBT_2_IIB_1,
        CONST_PSBSMP.V_V_DRIVER_IIB_1,
        CONST_PSBSMP.V_I_DRIVER_1_IIB_1,
        CONST_PSBSMP.V_I_DRIVER_2_IIB_1,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_1,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_1,
        CONST_PSBSMP.V_V_INPUT_IIB_2,
        CONST_PSBSMP.V_V_OUTPUT_IIB_2,
        CONST_PSBSMP.V_I_IGBT_1_IIB_2,
        CONST_PSBSMP.V_I_IGBT_2_IIB_2,
        CONST_PSBSMP.V_TEMP_IGBT_1_IIB_2,
        CONST_PSBSMP.V_TEMP_IGBT_2_IIB_2,
        CONST_PSBSMP.V_V_DRIVER_IIB_2,
        CONST_PSBSMP.V_I_DRIVER_1_IIB_2,
        CONST_PSBSMP.V_I_DRIVER_2_IIB_2,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_2,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_2,
        CONST_PSBSMP.V_V_INPUT_IIB_3,
        CONST_PSBSMP.V_V_OUTPUT_IIB_3,
        CONST_PSBSMP.V_I_IGBT_1_IIB_3,
        CONST_PSBSMP.V_I_IGBT_2_IIB_3,
        CONST_PSBSMP.V_TEMP_IGBT_1_IIB_3,
        CONST_PSBSMP.V_TEMP_IGBT_2_IIB_3,
        CONST_PSBSMP.V_V_DRIVER_IIB_3,
        CONST_PSBSMP.V_I_DRIVER_1_IIB_3,
        CONST_PSBSMP.V_I_DRIVER_2_IIB_3,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_3,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_3,
        CONST_PSBSMP.V_V_INPUT_IIB_4,
        CONST_PSBSMP.V_V_OUTPUT_IIB_4,
        CONST_PSBSMP.V_I_IGBT_1_IIB_4,
        CONST_PSBSMP.V_I_IGBT_2_IIB_4,
        CONST_PSBSMP.V_TEMP_IGBT_1_IIB_4,
        CONST_PSBSMP.V_TEMP_IGBT_2_IIB_4,
        CONST_PSBSMP.V_V_DRIVER_IIB_4,
        CONST_PSBSMP.V_I_DRIVER_1_IIB_4,
        CONST_PSBSMP.V_I_DRIVER_2_IIB_4,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_4,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_4,
        CONST_PSBSMP.V_IIB_INTERLOCKS_1,
        CONST_PSBSMP.V_IIB_INTERLOCKS_2,
        CONST_PSBSMP.V_IIB_INTERLOCKS_3,
        CONST_PSBSMP.V_IIB_INTERLOCKS_4,
        CONST_PSBSMP.V_I_MOD_1,
        CONST_PSBSMP.V_I_MOD_2,
        CONST_PSBSMP.V_I_MOD_3,
        CONST_PSBSMP.V_I_MOD_4)
    groups[_PRUCParms.SYNCOFF] = (
        # --- common variables
        CONST_PSBSMP.V_PS_STATUS,
        CONST_PSBSMP.V_PS_SETPOINT,
        CONST_PSBSMP.V_PS_REFERENCE,
        CONST_PSBSMP.V_FIRMWARE_VERSION,
        CONST_PSBSMP.V_COUNTER_SET_SLOWREF,
        CONST_PSBSMP.V_COUNTER_SYNC_PULSE,
        CONST_PSBSMP.V_SIGGEN_ENABLE,
        CONST_PSBSMP.V_SIGGEN_TYPE,
        CONST_PSBSMP.V_SIGGEN_NUM_CYCLES,
        CONST_PSBSMP.V_SIGGEN_N,
        CONST_PSBSMP.V_SIGGEN_FREQ,
        CONST_PSBSMP.V_SIGGEN_AMPLITUDE,
        CONST_PSBSMP.V_SIGGEN_OFFSET,
        CONST_PSBSMP.V_SIGGEN_AUX_PARAM,
        CONST_PSBSMP.V_WFMREF_SELECTED,
        CONST_PSBSMP.V_WFMREF_SYNC_MODE,
        CONST_PSBSMP.V_WFMREF_GAIN,
        CONST_PSBSMP.V_WFMREF_OFFSET,
        CONST_PSBSMP.V_WFMREF0_START,
        CONST_PSBSMP.V_WFMREF0_END,
        CONST_PSBSMP.V_WFMREF0_IDX,
        CONST_PSBSMP.V_WFMREF1_START,
        CONST_PSBSMP.V_WFMREF1_END,
        CONST_PSBSMP.V_WFMREF1_IDX,
        # --- FAP_2P2S variables ---
        CONST_PSBSMP.V_PS_SOFT_INTERLOCKS,
        CONST_PSBSMP.V_PS_HARD_INTERLOCKS,
        CONST_PSBSMP.V_I_LOAD_MEAN,
        CONST_PSBSMP.V_I_LOAD1,
        CONST_PSBSMP.V_I_LOAD2,
        CONST_PSBSMP.V_I_ARM_1,
        CONST_PSBSMP.V_I_ARM_2,
        CONST_PSBSMP.V_I_IGBT_1_1,
        CONST_PSBSMP.V_I_IGBT_2_1,
        CONST_PSBSMP.V_I_IGBT_1_2,
        CONST_PSBSMP.V_I_IGBT_2_2,
        CONST_PSBSMP.V_I_IGBT_1_3,
        CONST_PSBSMP.V_I_IGBT_2_3,
        CONST_PSBSMP.V_I_IGBT_1_4,
        CONST_PSBSMP.V_I_IGBT_2_4,
        CONST_PSBSMP.V_V_DCLINK_1,
        CONST_PSBSMP.V_V_DCLINK_2,
        CONST_PSBSMP.V_V_DCLINK_3,
        CONST_PSBSMP.V_V_DCLINK_4,
        CONST_PSBSMP.V_DUTY_MEAN,
        CONST_PSBSMP.V_DUTY_ARMS_DIFF,
        CONST_PSBSMP.V_DUTY_CYCLE_1_1,
        CONST_PSBSMP.V_DUTY_CYCLE_2_1,
        CONST_PSBSMP.V_DUTY_CYCLE_1_2,
        CONST_PSBSMP.V_DUTY_CYCLE_2_2,
        CONST_PSBSMP.V_DUTY_CYCLE_1_3,
        CONST_PSBSMP.V_DUTY_CYCLE_2_3,
        CONST_PSBSMP.V_DUTY_CYCLE_1_4,
        CONST_PSBSMP.V_DUTY_CYCLE_2_4,
        CONST_PSBSMP.V_V_INPUT_IIB_1,
        CONST_PSBSMP.V_V_OUTPUT_IIB_1,
        CONST_PSBSMP.V_I_IGBT_1_IIB_1,
        CONST_PSBSMP.V_I_IGBT_2_IIB_1,
        CONST_PSBSMP.V_TEMP_IGBT_1_IIB_1,
        CONST_PSBSMP.V_TEMP_IGBT_2_IIB_1,
        CONST_PSBSMP.V_V_DRIVER_IIB_1,
        CONST_PSBSMP.V_I_DRIVER_1_IIB_1,
        CONST_PSBSMP.V_I_DRIVER_2_IIB_1,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_1,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_1,
        CONST_PSBSMP.V_V_INPUT_IIB_2,
        CONST_PSBSMP.V_V_OUTPUT_IIB_2,
        CONST_PSBSMP.V_I_IGBT_1_IIB_2,
        CONST_PSBSMP.V_I_IGBT_2_IIB_2,
        CONST_PSBSMP.V_TEMP_IGBT_1_IIB_2,
        CONST_PSBSMP.V_TEMP_IGBT_2_IIB_2,
        CONST_PSBSMP.V_V_DRIVER_IIB_2,
        CONST_PSBSMP.V_I_DRIVER_1_IIB_2,
        CONST_PSBSMP.V_I_DRIVER_2_IIB_2,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_2,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_2,
        CONST_PSBSMP.V_V_INPUT_IIB_3,
        CONST_PSBSMP.V_V_OUTPUT_IIB_3,
        CONST_PSBSMP.V_I_IGBT_1_IIB_3,
        CONST_PSBSMP.V_I_IGBT_2_IIB_3,
        CONST_PSBSMP.V_TEMP_IGBT_1_IIB_3,
        CONST_PSBSMP.V_TEMP_IGBT_2_IIB_3,
        CONST_PSBSMP.V_V_DRIVER_IIB_3,
        CONST_PSBSMP.V_I_DRIVER_1_IIB_3,
        CONST_PSBSMP.V_I_DRIVER_2_IIB_3,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_3,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_3,
        CONST_PSBSMP.V_V_INPUT_IIB_4,
        CONST_PSBSMP.V_V_OUTPUT_IIB_4,
        CONST_PSBSMP.V_I_IGBT_1_IIB_4,
        CONST_PSBSMP.V_I_IGBT_2_IIB_4,
        CONST_PSBSMP.V_TEMP_IGBT_1_IIB_4,
        CONST_PSBSMP.V_TEMP_IGBT_2_IIB_4,
        CONST_PSBSMP.V_V_DRIVER_IIB_4,
        CONST_PSBSMP.V_I_DRIVER_1_IIB_4,
        CONST_PSBSMP.V_I_DRIVER_2_IIB_4,
        CONST_PSBSMP.V_TEMP_INDUCTOR_IIB_4,
        CONST_PSBSMP.V_TEMP_HEATSINK_IIB_4,
        CONST_PSBSMP.V_IIB_INTERLOCKS_1,
        CONST_PSBSMP.V_IIB_INTERLOCKS_2,
        CONST_PSBSMP.V_IIB_INTERLOCKS_3,
        CONST_PSBSMP.V_IIB_INTERLOCKS_4,
        CONST_PSBSMP.V_I_MOD_1,
        CONST_PSBSMP.V_I_MOD_2,
        CONST_PSBSMP.V_I_MOD_3,
        CONST_PSBSMP.V_I_MOD_4)
    groups[_PRUCParms.MIRROR] = groups[_PRUCParms.SYNCOFF]
