"""Parameters of the IOCs of the AP discipline."""
from copy import deepcopy as _dcopy

_off = 0
_on = 1


def get_dict():
    """Return configuration type dictionary."""
    module_name = __name__.split('.')[-1]
    _dict = {
        'config_type_name': module_name,
        'value': _dcopy(_template_dict)
    }
    return _dict


# When using this type of configuration to set the machine,
# the list of PVs should be processed in the same order they are stored
# in the configuration. The second numeric parameter in the pair is the
# delay [s] the client should wait before setting the next PV.

_tb_sofb = [
    ['TB-Glob:AP-SOFB:BPMXEnblList-SP', [0, ]*6, 0.0],
    ['TB-Glob:AP-SOFB:BPMYEnblList-SP', [0, ]*6, 0.0],
    ['TB-Glob:AP-SOFB:CHEnblList-SP', [0, ]*5, 0.0],
    ['TB-Glob:AP-SOFB:CVEnblList-SP', [0, ]*6, 0.0],
    ['TB-Glob:AP-SOFB:CorrFactorCH-SP', 0.0, 0.0],
    ['TB-Glob:AP-SOFB:CorrFactorCV-SP', 0.0, 0.0],
    ['TB-Glob:AP-SOFB:KickAcqRate-SP', 0.0, 0.0],
    ['TB-Glob:AP-SOFB:MaxDeltaKickCH-SP', 0.0, 0.0],
    ['TB-Glob:AP-SOFB:MaxDeltaKickCV-SP', 0.0, 0.0],
    ['TB-Glob:AP-SOFB:MaxKickCH-SP', 0.0, 0.0],
    ['TB-Glob:AP-SOFB:MaxKickCV-SP', 0.0, 0.0],
    ['TB-Glob:AP-SOFB:MeasRespMatKickCH-SP', 0.0, 0.0],
    ['TB-Glob:AP-SOFB:MeasRespMatKickCV-SP', 0.0, 0.0],
    ['TB-Glob:AP-SOFB:MeasRespMatWait-SP', 0.0, 0.0],
    ['TB-Glob:AP-SOFB:NumSingValues-SP', 0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitAcqRate-SP', 0.0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitMode-Sel', 0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitOfflineX-SP', [0.0, ]*6, 0.0],
    ['TB-Glob:AP-SOFB:OrbitOfflineY-SP', [0.0, ]*6, 0.0],
    ['TB-Glob:AP-SOFB:OrbitRefX-SP', [0.0, ]*6, 0.0],
    ['TB-Glob:AP-SOFB:OrbitRefY-SP', [0.0, ]*6, 0.0],
    ['TB-Glob:AP-SOFB:OrbitSmoothMethod-Sel', 0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitSmoothNPnts-SP', 0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitTrigAcqChan-Sel', 0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitTrigAcqCtrl-Sel', 0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitTrigAcqRepeat-Sel', 0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitTrigAcqTrigger-Sel', 0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitTrigDataChan-Sel', 0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitTrigDataHyst-SP', 0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitTrigDataPol-Sel', 0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitTrigDataSel-Sel', 0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitTrigDataThres-SP', 0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitTrigExtDelay-SP', 0.0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitTrigExtDuration-SP', 0.0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitTrigExtEvtSrc-Sel', 0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitTrigNrSamplesPost-SP', 0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitTrigNrSamplesPre-SP', 0, 0.0],
    ['TB-Glob:AP-SOFB:OrbitTrigNrShots-SP', 0, 0.0],
    ['TB-Glob:AP-SOFB:RespMat-SP', [0.0, ]*132, 0.0],
]

_bo_sofb = [
    ['BO-Glob:AP-SOFB:AutoCorrFreq-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:BPMXEnblList-SP', [0, ]*50, 0.0],
    ['BO-Glob:AP-SOFB:BPMYEnblList-SP', [0, ]*50, 0.0],
    ['BO-Glob:AP-SOFB:CHEnblList-SP', [0, ]*25, 0.0],
    ['BO-Glob:AP-SOFB:CVEnblList-SP', [0, ]*25, 0.0],
    ['BO-Glob:AP-SOFB:CorrFactorCH-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:CorrFactorCV-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:CorrFactorRF-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:KickAcqRate-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:MaxDeltaKickCH-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:MaxDeltaKickCV-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:MaxDeltaKickRF-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:MaxKickCH-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:MaxKickCV-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:MaxKickRF-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:MeasRespMatKickCH-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:MeasRespMatKickCV-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:MeasRespMatKickRF-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:MeasRespMatWait-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:NominalFreqRF-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:NumSingValues-SP', 0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitAcqRate-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitMode-Sel', 0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitMultiTurnIdx-SP', 0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitOfflineX-SP', [0.0, ]*50, 0.0],
    ['BO-Glob:AP-SOFB:OrbitOfflineY-SP', [0.0, ]*50, 0.0],
    ['BO-Glob:AP-SOFB:OrbitRefX-SP', [0.0, ]*50, 0.0],
    ['BO-Glob:AP-SOFB:OrbitRefY-SP', [0.0, ]*50, 0.0],
    ['BO-Glob:AP-SOFB:OrbitSmoothMethod-Sel', 0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitSmoothNPnts-SP', 0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitTrigAcqChan-Sel', 0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitTrigAcqCtrl-Sel', 0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitTrigAcqRepeat-Sel', 0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitTrigAcqTrigger-Sel', 0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitTrigDataChan-Sel', 0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitTrigDataHyst-SP', 0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitTrigDataPol-Sel', 0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitTrigDataSel-Sel', 0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitTrigDataThres-SP', 0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitTrigDownSample-SP', 0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitTrigExtDelay-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitTrigExtDuration-SP', 0.0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitTrigExtEvtSrc-Sel', 0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitTrigNrSamplesPost-SP', 0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitTrigNrSamplesPre-SP', 0, 0.0],
    ['BO-Glob:AP-SOFB:OrbitTrigNrShots-SP', 0, 0.0],
    ['BO-Glob:AP-SOFB:RFEnbl-Sel', 0, 0.0],
    ['BO-Glob:AP-SOFB:RespMat-SP', [0.0, ]*5100, 0.0],
    ['BO-Glob:AP-SOFB:SyncKicks-Sel', 0, 0.0],
]

_ts_sofb = [
    ['TS-Glob:AP-SOFB:BPMXEnblList-SP', [0, ]*5, 0.0],
    ['TS-Glob:AP-SOFB:BPMYEnblList-SP', [0, ]*5, 0.0],
    ['TS-Glob:AP-SOFB:CHEnblList-SP', [0, ]*4, 0.0],
    ['TS-Glob:AP-SOFB:CVEnblList-SP', [0, ]*6, 0.0],
    ['TS-Glob:AP-SOFB:CorrFactorCH-SP', 0.0, 0.0],
    ['TS-Glob:AP-SOFB:CorrFactorCV-SP', 0.0, 0.0],
    ['TS-Glob:AP-SOFB:KickAcqRate-SP', 0.0, 0.0],
    ['TS-Glob:AP-SOFB:MaxDeltaKickCH-SP', 0.0, 0.0],
    ['TS-Glob:AP-SOFB:MaxDeltaKickCV-SP', 0.0, 0.0],
    ['TS-Glob:AP-SOFB:MaxKickCH-SP', 0.0, 0.0],
    ['TS-Glob:AP-SOFB:MaxKickCV-SP', 0.0, 0.0],
    ['TS-Glob:AP-SOFB:MeasRespMatKickCH-SP', 0.0, 0.0],
    ['TS-Glob:AP-SOFB:MeasRespMatKickCV-SP', 0.0, 0.0],
    ['TS-Glob:AP-SOFB:MeasRespMatWait-SP', 0.0, 0.0],
    ['TS-Glob:AP-SOFB:NumSingValues-SP', 0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitAcqRate-SP', 0.0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitMode-Sel', 0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitOfflineX-SP', [0.0, ]*5, 0.0],
    ['TS-Glob:AP-SOFB:OrbitOfflineY-SP', [0.0, ]*5, 0.0],
    ['TS-Glob:AP-SOFB:OrbitRefX-SP', [0.0, ]*5, 0.0],
    ['TS-Glob:AP-SOFB:OrbitRefY-SP', [0.0, ]*5, 0.0],
    ['TS-Glob:AP-SOFB:OrbitSmoothMethod-Sel', 0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitSmoothNPnts-SP', 0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitTrigAcqChan-Sel', 0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitTrigAcqCtrl-Sel', 0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitTrigAcqRepeat-Sel', 0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitTrigAcqTrigger-Sel', 0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitTrigDataChan-Sel', 0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitTrigDataHyst-SP', 0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitTrigDataPol-Sel', 0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitTrigDataSel-Sel', 0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitTrigDataThres-SP', 0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitTrigExtDelay-SP', 0.0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitTrigExtDuration-SP', 0.0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitTrigExtEvtSrc-Sel', 0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitTrigNrSamplesPost-SP', 0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitTrigNrSamplesPre-SP', 0, 0.0],
    ['TS-Glob:AP-SOFB:OrbitTrigNrShots-SP', 0, 0.0],
    ['TS-Glob:AP-SOFB:RespMat-SP', [0.0, ]*100, 0.0],
]

_si_sofb = [
    ['SI-Glob:AP-SOFB:AutoCorrFreq-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:BPMXEnblList-SP', [0, ]*160, 0.0],
    ['SI-Glob:AP-SOFB:BPMYEnblList-SP', [0, ]*160, 0.0],
    ['SI-Glob:AP-SOFB:CHEnblList-SP', [0, ]*120, 0.0],
    ['SI-Glob:AP-SOFB:CVEnblList-SP', [0, ]*160, 0.0],
    ['SI-Glob:AP-SOFB:CorrFactorCH-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:CorrFactorCV-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:CorrFactorRF-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:KickAcqRate-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:MaxDeltaKickCH-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:MaxDeltaKickCV-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:MaxDeltaKickRF-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:MaxKickCH-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:MaxKickCV-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:MaxKickRF-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:MeasRespMatKickCH-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:MeasRespMatKickCV-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:MeasRespMatKickRF-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:MeasRespMatWait-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:NominalFreqRF-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:NumSingValues-SP', 0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitAcqRate-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitMode-Sel', 0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitMultiTurnIdx-SP', 0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitOfflineX-SP', [0.0, ]*160, 0.0],
    ['SI-Glob:AP-SOFB:OrbitOfflineY-SP', [0.0, ]*160, 0.0],
    ['SI-Glob:AP-SOFB:OrbitRefX-SP', [0.0, ]*160, 0.0],
    ['SI-Glob:AP-SOFB:OrbitRefY-SP', [0.0, ]*160, 0.0],
    ['SI-Glob:AP-SOFB:OrbitSmoothMethod-Sel', 0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitSmoothNPnts-SP', 0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitTrigAcqChan-Sel', 0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitTrigAcqCtrl-Sel', 0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitTrigAcqRepeat-Sel', 0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitTrigAcqTrigger-Sel', 0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitTrigDataChan-Sel', 0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitTrigDataHyst-SP', 0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitTrigDataPol-Sel', 0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitTrigDataSel-Sel', 0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitTrigDataThres-SP', 0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitTrigDownSample-SP', 0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitTrigExtDelay-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitTrigExtDuration-SP', 0.0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitTrigExtEvtSrc-Sel', 0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitTrigNrSamplesPost-SP', 0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitTrigNrSamplesPre-SP', 0, 0.0],
    ['SI-Glob:AP-SOFB:OrbitTrigNrShots-SP', 0, 0.0],
    ['SI-Glob:AP-SOFB:RFEnbl-Sel', 0, 0.0],
    ['SI-Glob:AP-SOFB:RespMat-SP', [0.0, ]*89920, 0.0],
    ['SI-Glob:AP-SOFB:SyncKicks-Sel', 0, 0.0],
]

_sofb = _tb_sofb + _bo_sofb + _ts_sofb + _si_sofb

_template_dict = {'pvs': _sofb}
