"""LI low level RF configuration."""
from copy import deepcopy as _dcopy


_off = 0


def get_dict():
    """Return configuration type dictionary."""
    module_name = __name__.split('.')[-1]
    _dict = {
        'config_type_name': module_name,
        'value': _dcopy(_template_dict)
    }
    return _dict


# When using this type of configuration to set the machine,
# the list of PVs should be processed in the same order they are stored
# in the configuration. The second numeric parameter in the pair is the
# delay [s] the client should wait before setting the next PV.

_pvs_li_llrf = [
    ['LA-RF:LLRF:BUN1:SET_STREAM', 0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_CH1_DELAY', 0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_CH2_DELAY', 0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_CH7_DELAY', 0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_CH8_DELAY', 0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_TRIGGER_DELAY', 0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_AMP', 0.0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_PHASE', 0.0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_FB_MODE', 0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_KP', 0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_KI', 0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_EXTERNAL_TRIGGER_ENABLE', 0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_INTEGRAL_ENABLE', 0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_CH1_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_CH2_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_CH7_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_CH8_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_FBLOOP_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_FBLOOP_AMP_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_CH1_ADT', 0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_CH2_ADT', 0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_CH7_ADT', 0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_CH8_ADT', 0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_VM_ADT', 0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_CH1_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_CH2_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_CH7_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_CH8_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_PID_MODE', 0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_PID_KP', 0, 0.0],
    ['LA-RF:LLRF:BUN1:SET_PID_KI', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_STREAM', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH1_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH2_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH3_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH4_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH5_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH6_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH7_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH8_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH9_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_TRIGGER_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_AMP', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_PHASE', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_FB_MODE', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_KP', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_KI', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_EXTERNAL_TRIGGER_ENABLE', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_INTEGRAL_ENABLE', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_FBLOOP_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_FBLOOP_AMP_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH1_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH2_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH3_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH4_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH5_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH6_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH7_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH8_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH9_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_FBLOOP_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_FBLOOP_AMP_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH1_ADT', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH2_ADT', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH3_ADT', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH4_ADT', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH5_ADT', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH6_ADT', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH7_ADT', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH8_ADT', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_VM_ADT', 0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH1_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH2_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH3_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH4_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH5_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH6_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH7_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH8_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_CH9_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:KLY1:SET_SHIF_MOTOR_ANGLE', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_STREAM', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH1_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH2_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH3_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH4_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH5_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH6_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH7_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH8_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH9_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_TRIGGER_DELAY', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_AMP', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_PHASE', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_FB_MODE', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_KP', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_KI', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_EXTERNAL_TRIGGER_ENABLE', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_INTEGRAL_ENABLE', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_FBLOOP_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_FBLOOP_AMP_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH1_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH2_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH3_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH4_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH5_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH6_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH7_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH8_PHASE_CORR', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH1_ADT', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH2_ADT', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH3_ADT', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH4_ADT', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH5_ADT', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH6_ADT', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH7_ADT', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH8_ADT', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_VM_ADT', 0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH1_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH2_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH3_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH4_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH5_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH6_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH7_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH8_ATT', 0.0, 0.0],
    ['LA-RF:LLRF:KLY2:SET_CH9_ATT', 0.0, 0.0],
    ]

_pvs_li_hl_timing = [
    ['RA-RaMO:TI-EVG:LinacMode-Sel', 0, 0.0],
    ['RA-RaMO:TI-EVG:DigLIMode-Sel', 0, 0.0],

    ['RA-RaMO:TI-EVG:LinacDelayType-Sel', 0, 0.0],
    ['RA-RaMO:TI-EVG:DigLIDelayType-Sel', 0, 0.0],

    ['RA-RaMO:TI-EVG:LinacDelay-SP', 0.0, 0.0],
    ['RA-RaMO:TI-EVG:DigLIDelay-SP', 0.0, 0.0],

    ['LI-01:TI-EGun-MultBun:State-Sel', 0, 0.0],
    ['LI-01:TI-EGun-SglBun:State-Sel', 0, 0.0],
    ['LI-01:TI-Modltr-1:State-Sel', 0, 0.0],
    ['LI-01:TI-Modltr-2:State-Sel', 0, 0.0],
    ['LI-Fam:TI-BPM:State-Sel', 0, 0.0],
    ['LI-Fam:TI-ICT:State-Sel', 0, 0.0],
    ['LI-Fam:TI-Scrn:State-Sel', 0, 0.0],
    ['LI-Glob:TI-LLRF-Kly1:State-Sel', 0, 0.0],
    ['LI-Glob:TI-LLRF-Kly2:State-Sel', 0, 0.0],
    ['LI-Glob:TI-LLRF-SHB:State-Sel', 0, 0.0],
    ['LI-Glob:TI-SSAmp-Kly1:State-Sel', 0, 0.0],
    ['LI-Glob:TI-SSAmp-Kly2:State-Sel', 0, 0.0],
    ['LI-Glob:TI-SSAmp-SHB:State-Sel', 0, 0.0],

    ['LI-01:TI-EGun-MultBun:Polarity-Sel', 0, 0.0],
    ['LI-01:TI-EGun-SglBun:Polarity-Sel', 0, 0.0],
    ['LI-01:TI-Modltr-1:Polarity-Sel', 0, 0.0],
    ['LI-01:TI-Modltr-2:Polarity-Sel', 0, 0.0],
    ['LI-Fam:TI-BPM:Polarity-Sel', 0, 0.0],
    ['LI-Fam:TI-ICT:Polarity-Sel', 0, 0.0],
    ['LI-Fam:TI-Scrn:Polarity-Sel', 0, 0.0],
    ['LI-Glob:TI-LLRF-Kly1:Polarity-Sel', 0, 0.0],
    ['LI-Glob:TI-LLRF-Kly2:Polarity-Sel', 0, 0.0],
    ['LI-Glob:TI-LLRF-SHB:Polarity-Sel', 0, 0.0],
    ['LI-Glob:TI-SSAmp-Kly1:Polarity-Sel', 0, 0.0],
    ['LI-Glob:TI-SSAmp-Kly2:Polarity-Sel', 0, 0.0],
    ['LI-Glob:TI-SSAmp-SHB:Polarity-Sel', 0, 0.0],

    ['LI-01:TI-EGun-MultBun:Src-Sel', 0, 0.0],
    ['LI-01:TI-EGun-SglBun:Src-Sel', 0, 0.0],
    ['LI-01:TI-Modltr-1:Src-Sel', 0, 0.0],
    ['LI-01:TI-Modltr-2:Src-Sel', 0, 0.0],
    ['LI-Fam:TI-BPM:Src-Sel', 0, 0.0],
    ['LI-Fam:TI-ICT:Src-Sel', 0, 0.0],
    ['LI-Fam:TI-Scrn:Src-Sel', 0, 0.0],
    ['LI-Glob:TI-LLRF-Kly1:Src-Sel', 0, 0.0],
    ['LI-Glob:TI-LLRF-Kly2:Src-Sel', 0, 0.0],
    ['LI-Glob:TI-LLRF-SHB:Src-Sel', 0, 0.0],
    ['LI-Glob:TI-SSAmp-Kly1:Src-Sel', 0, 0.0],
    ['LI-Glob:TI-SSAmp-Kly2:Src-Sel', 0, 0.0],
    ['LI-Glob:TI-SSAmp-SHB:Src-Sel', 0, 0.0],

    ['LI-01:TI-EGun-MultBun:NrPulses-SP', 0, 0.0],
    ['LI-01:TI-EGun-SglBun:NrPulses-SP', 0, 0.0],
    ['LI-01:TI-Modltr-1:NrPulses-SP', 0, 0.0],
    ['LI-01:TI-Modltr-2:NrPulses-SP', 0, 0.0],
    ['LI-Fam:TI-BPM:NrPulses-SP', 0, 0.0],
    ['LI-Fam:TI-ICT:NrPulses-SP', 0, 0.0],
    ['LI-Fam:TI-Scrn:NrPulses-SP', 0, 0.0],
    ['LI-Glob:TI-LLRF-Kly1:NrPulses-SP', 0, 0.0],
    ['LI-Glob:TI-LLRF-Kly2:NrPulses-SP', 0, 0.0],
    ['LI-Glob:TI-LLRF-SHB:NrPulses-SP', 0, 0.0],
    ['LI-Glob:TI-SSAmp-Kly1:NrPulses-SP', 0, 0.0],
    ['LI-Glob:TI-SSAmp-Kly2:NrPulses-SP', 0, 0.0],
    ['LI-Glob:TI-SSAmp-SHB:NrPulses-SP', 0, 0.0],

    ['LI-01:TI-EGun-MultBun:Duration-SP', 0.0, 0.0],
    ['LI-01:TI-EGun-SglBun:Duration-SP', 0.0, 0.0],
    ['LI-01:TI-Modltr-1:Duration-SP', 0.0, 0.0],
    ['LI-01:TI-Modltr-2:Duration-SP', 0.0, 0.0],
    ['LI-Fam:TI-BPM:Duration-SP', 0.0, 0.0],
    ['LI-Fam:TI-ICT:Duration-SP', 0.0, 0.0],
    ['LI-Fam:TI-Scrn:Duration-SP', 0.0, 0.0],
    ['LI-Glob:TI-LLRF-Kly1:Duration-SP', 0.0, 0.0],
    ['LI-Glob:TI-LLRF-Kly2:Duration-SP', 0.0, 0.0],
    ['LI-Glob:TI-LLRF-SHB:Duration-SP', 0.0, 0.0],
    ['LI-Glob:TI-SSAmp-Kly1:Duration-SP', 0.0, 0.0],
    ['LI-Glob:TI-SSAmp-Kly2:Duration-SP', 0.0, 0.0],
    ['LI-Glob:TI-SSAmp-SHB:Duration-SP', 0.0, 0.0],

    ['LI-01:TI-EGun-MultBun:Delay-SP', 0.0, 0.0],
    ['LI-01:TI-EGun-SglBun:Delay-SP', 0.0, 0.0],
    ['LI-01:TI-Modltr-1:Delay-SP', 0.0, 0.0],
    ['LI-01:TI-Modltr-2:Delay-SP', 0.0, 0.0],
    ['LI-Fam:TI-BPM:Delay-SP', 0.0, 0.0],
    ['LI-Fam:TI-ICT:Delay-SP', 0.0, 0.0],
    ['LI-Fam:TI-Scrn:Delay-SP', 0.0, 0.0],
    ['LI-Glob:TI-LLRF-Kly1:Delay-SP', 0.0, 0.0],
    ['LI-Glob:TI-LLRF-Kly2:Delay-SP', 0.0, 0.0],
    ['LI-Glob:TI-LLRF-SHB:Delay-SP', 0.0, 0.0],
    ['LI-Glob:TI-SSAmp-Kly1:Delay-SP', 0.0, 0.0],
    ['LI-Glob:TI-SSAmp-Kly2:Delay-SP', 0.0, 0.0],
    ['LI-Glob:TI-SSAmp-SHB:Delay-SP', 0.0, 0.0],

    ['LI-01:TI-EGun-MultBun:ByPassIntlk-Sel', 0, 0.0],
    ['LI-01:TI-EGun-SglBun:ByPassIntlk-Sel', 0, 0.0],
    ['LI-01:TI-Modltr-1:ByPassIntlk-Sel', 0, 0.0],
    ['LI-01:TI-Modltr-2:ByPassIntlk-Sel', 0, 0.0],
    ['LI-Fam:TI-BPM:ByPassIntlk-Sel', 0, 0.0],
    ['LI-Fam:TI-ICT:ByPassIntlk-Sel', 0, 0.0],
    ['LI-Fam:TI-Scrn:ByPassIntlk-Sel', 0, 0.0],
    ['LI-Glob:TI-LLRF-Kly1:ByPassIntlk-Sel', 0, 0.0],
    ['LI-Glob:TI-LLRF-Kly2:ByPassIntlk-Sel', 0, 0.0],
    ['LI-Glob:TI-LLRF-SHB:ByPassIntlk-Sel', 0, 0.0],
    ['LI-Glob:TI-SSAmp-Kly1:ByPassIntlk-Sel', 0, 0.0],
    ['LI-Glob:TI-SSAmp-Kly2:ByPassIntlk-Sel', 0, 0.0],
    ['LI-Glob:TI-SSAmp-SHB:ByPassIntlk-Sel', 0, 0.0],

    ['LI-01:TI-EGun-MultBun:RFDelayType-Sel', 0, 0.0],
    ['LI-01:TI-EGun-SglBun:RFDelayType-Sel', 0, 0.0],
    # ['LI-01:TI-Modltr-1:RFDelayType-Sel', 0, 0.0],
    # ['LI-01:TI-Modltr-2:RFDelayType-Sel', 0, 0.0],
    ['LI-Fam:TI-BPM:RFDelayType-Sel', 0, 0.0],
    ['LI-Fam:TI-ICT:RFDelayType-Sel', 0, 0.0],
    ['LI-Fam:TI-Scrn:RFDelayType-Sel', 0, 0.0],
    # ['LI-Glob:TI-LLRF-Kly1:RFDelayType-Sel', 0, 0.0],
    # ['LI-Glob:TI-LLRF-Kly2:RFDelayType-Sel', 0, 0.0],
    # ['LI-Glob:TI-LLRF-SHB:RFDelayType-Sel', 0, 0.0],
    # ['LI-Glob:TI-SSAmp-Kly1:RFDelayType-Sel', 0, 0.0],
    # ['LI-Glob:TI-SSAmp-Kly2:RFDelayType-Sel', 0, 0.0],
    # ['LI-Glob:TI-SSAmp-SHB:RFDelayType-Sel', 0, 0.0],
    ]

_pvs_li_pwrsupplies = [
    ['LA-CN:H1MLPS-1:setpwm', _off, 0.0],
    ['LA-CN:H1MLPS-2:setpwm', _off, 0.0],
    ['LA-CN:H1MLPS-3:setpwm', _off, 0.0],
    ['LA-CN:H1MLPS-4:setpwm', _off, 0.0],
    ['LA-CN:H1SCPS-1:setpwm', _off, 0.0],
    ['LA-CN:H1SCPS-2:setpwm', _off, 0.0],
    ['LA-CN:H1SCPS-3:setpwm', _off, 0.0],
    ['LA-CN:H1SCPS-4:setpwm', _off, 0.0],
    ['LA-CN:H1LCPS-1:setpwm', _off, 0.0],
    ['LA-CN:H1LCPS-2:setpwm', _off, 0.0],
    ['LA-CN:H1LCPS-3:setpwm', _off, 0.0],
    ['LA-CN:H1LCPS-4:setpwm', _off, 0.0],
    ['LA-CN:H1LCPS-5:setpwm', _off, 0.0],
    ['LA-CN:H1LCPS-6:setpwm', _off, 0.0],
    ['LA-CN:H1LCPS-7:setpwm', _off, 0.0],
    ['LA-CN:H1LCPS-8:setpwm', _off, 0.0],
    ['LA-CN:H1LCPS-9:setpwm', _off, 0.0],
    ['LA-CN:H1LCPS-10:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-1:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-2:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-3:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-4:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-5:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-6:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-7:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-8:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-9:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-10:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-11:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-12:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-13:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-14:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-15:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-16:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-17:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-18:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-19:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-20:setpwm', _off, 0.0],
    ['LA-CN:H1SLPS-21:setpwm', _off, 0.0],
    ['LA-CN:H1FQPS-1:setpwm', _off, 0.0],
    ['LA-CN:H1FQPS-2:setpwm', _off, 0.0],
    ['LA-CN:H1FQPS-3:setpwm', _off, 0.0],
    ['LA-CN:H1DQPS-1:setpwm', _off, 0.0],
    ['LA-CN:H1DQPS-2:setpwm', _off, 0.0],
    ['LA-CN:H1RCPS-1:setpwm', _off, 0.0],
    ['LA-CN:H1DPPS-1:setpwm', _off, 2.0],
    ['LA-CN:H1MLPS-1:seti', 0.0, 0.0],
    ['LA-CN:H1MLPS-2:seti', 0.0, 0.0],
    ['LA-CN:H1MLPS-3:seti', 0.0, 0.0],
    ['LA-CN:H1MLPS-4:seti', 0.0, 0.0],
    ['LA-CN:H1SCPS-1:seti', 0.0, 0.0],
    ['LA-CN:H1SCPS-2:seti', 0.0, 0.0],
    ['LA-CN:H1SCPS-3:seti', 0.0, 0.0],
    ['LA-CN:H1SCPS-4:seti', 0.0, 0.0],
    ['LA-CN:H1LCPS-1:seti', 0.0, 0.0],
    ['LA-CN:H1LCPS-2:seti', 0.0, 0.0],
    ['LA-CN:H1LCPS-3:seti', 0.0, 0.0],
    ['LA-CN:H1LCPS-4:seti', 0.0, 0.0],
    ['LA-CN:H1LCPS-5:seti', 0.0, 0.0],
    ['LA-CN:H1LCPS-6:seti', 0.0, 0.0],
    ['LA-CN:H1LCPS-7:seti', 0.0, 0.0],
    ['LA-CN:H1LCPS-8:seti', 0.0, 0.0],
    ['LA-CN:H1LCPS-9:seti', 0.0, 0.0],
    ['LA-CN:H1LCPS-10:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-1:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-2:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-3:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-4:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-5:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-6:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-7:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-8:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-9:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-10:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-11:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-12:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-13:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-14:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-15:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-16:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-17:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-18:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-19:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-20:seti', 0.0, 0.0],
    ['LA-CN:H1SLPS-21:seti', 0.0, 0.0],
    ['LA-CN:H1FQPS-1:seti', 0.0, 0.0],
    ['LA-CN:H1FQPS-2:seti', 0.0, 0.0],
    ['LA-CN:H1FQPS-3:seti', 0.0, 0.0],
    ['LA-CN:H1DQPS-1:seti', 0.0, 0.0],
    ['LA-CN:H1DQPS-2:seti', 0.0, 0.0],
    ['LA-CN:H1RCPS-1:seti', 0.0, 0.0],
    ['LA-CN:H1DPPS-1:seti', 0.0, 0.0],
    ]

_pvs_tb_ma = [
    ['TB-Fam:MA-B:PwrState-Sel', _off, 0.0],
    ['TB-01:MA-QD1:PwrState-Sel', _off, 0.0],
    ['TB-01:MA-QF1:PwrState-Sel', _off, 0.0],
    ['TB-02:MA-QD2A:PwrState-Sel', _off, 0.0],
    ['TB-02:MA-QF2A:PwrState-Sel', _off, 0.0],
    ['TB-02:MA-QF2B:PwrState-Sel', _off, 0.0],
    ['TB-02:MA-QD2B:PwrState-Sel', _off, 0.0],
    ['TB-03:MA-QF3:PwrState-Sel', _off, 0.0],
    ['TB-03:MA-QD3:PwrState-Sel', _off, 0.0],
    ['TB-04:MA-QF4:PwrState-Sel', _off, 0.0],
    ['TB-04:MA-QD4:PwrState-Sel', _off, 0.0],
    ['TB-01:MA-CH-1:PwrState-Sel', _off, 0.0],
    ['TB-01:MA-CV-1:PwrState-Sel', _off, 0.0],
    ['TB-01:MA-CH-2:PwrState-Sel', _off, 0.0],
    ['TB-01:MA-CV-2:PwrState-Sel', _off, 0.0],
    ['TB-02:MA-CH-1:PwrState-Sel', _off, 0.0],
    ['TB-02:MA-CV-1:PwrState-Sel', _off, 0.0],
    ['TB-02:MA-CH-2:PwrState-Sel', _off, 0.0],
    ['TB-02:MA-CV-2:PwrState-Sel', _off, 0.0],
    ['TB-04:MA-CH:PwrState-Sel', _off, 0.0],
    ['TB-04:MA-CV-1:PwrState-Sel', _off, 0.0],
    ['TB-04:MA-CV-2:PwrState-Sel', _off, 0.0],

    ['TB-Fam:MA-B:OpMode-Sel', _off, 0.0],
    ['TB-01:MA-QD1:OpMode-Sel', _off, 0.0],
    ['TB-01:MA-QF1:OpMode-Sel', _off, 0.0],
    ['TB-02:MA-QD2A:OpMode-Sel', _off, 0.0],
    ['TB-02:MA-QF2A:OpMode-Sel', _off, 0.0],
    ['TB-02:MA-QF2B:OpMode-Sel', _off, 0.0],
    ['TB-02:MA-QD2B:OpMode-Sel', _off, 0.0],
    ['TB-03:MA-QF3:OpMode-Sel', _off, 0.0],
    ['TB-03:MA-QD3:OpMode-Sel', _off, 0.0],
    ['TB-04:MA-QF4:OpMode-Sel', _off, 0.0],
    ['TB-04:MA-QD4:OpMode-Sel', _off, 0.0],
    ['TB-01:MA-CH-1:OpMode-Sel', _off, 0.0],
    ['TB-01:MA-CV-1:OpMode-Sel', _off, 0.0],
    ['TB-01:MA-CH-2:OpMode-Sel', _off, 0.0],
    ['TB-01:MA-CV-2:OpMode-Sel', _off, 0.0],
    ['TB-02:MA-CH-1:OpMode-Sel', _off, 0.0],
    ['TB-02:MA-CV-1:OpMode-Sel', _off, 0.0],
    ['TB-02:MA-CH-2:OpMode-Sel', _off, 0.0],
    ['TB-02:MA-CV-2:OpMode-Sel', _off, 0.0],
    ['TB-04:MA-CH:OpMode-Sel', _off, 0.0],
    ['TB-04:MA-CV-1:OpMode-Sel', _off, 0.0],
    ['TB-04:MA-CV-2:OpMode-Sel', _off, 0.0],

    ['TB-Fam:MA-B:BSMPComm-Sel', _off, 0.0],
    ['TB-01:MA-QD1:BSMPComm-Sel', _off, 0.0],
    ['TB-01:MA-QF1:BSMPComm-Sel', _off, 0.0],
    ['TB-02:MA-QD2A:BSMPComm-Sel', _off, 0.0],
    ['TB-02:MA-QF2A:BSMPComm-Sel', _off, 0.0],
    ['TB-02:MA-QF2B:BSMPComm-Sel', _off, 0.0],
    ['TB-02:MA-QD2B:BSMPComm-Sel', _off, 0.0],
    ['TB-03:MA-QF3:BSMPComm-Sel', _off, 0.0],
    ['TB-03:MA-QD3:BSMPComm-Sel', _off, 0.0],
    ['TB-04:MA-QF4:BSMPComm-Sel', _off, 0.0],
    ['TB-04:MA-QD4:BSMPComm-Sel', _off, 0.0],
    ['TB-01:MA-CH-1:BSMPComm-Sel', _off, 0.0],
    ['TB-01:MA-CV-1:BSMPComm-Sel', _off, 0.0],
    ['TB-01:MA-CH-2:BSMPComm-Sel', _off, 0.0],
    ['TB-01:MA-CV-2:BSMPComm-Sel', _off, 0.0],
    ['TB-02:MA-CH-1:BSMPComm-Sel', _off, 0.0],
    ['TB-02:MA-CV-1:BSMPComm-Sel', _off, 0.0],
    ['TB-02:MA-CH-2:BSMPComm-Sel', _off, 0.0],
    ['TB-02:MA-CV-2:BSMPComm-Sel', _off, 0.0],
    ['TB-04:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['TB-04:MA-CV-1:BSMPComm-Sel', _off, 0.0],
    ['TB-04:MA-CV-2:BSMPComm-Sel', _off, 0.0],

    ['TB-Fam:MA-B:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-01:MA-QD1:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-01:MA-QF1:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-02:MA-QD2A:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-02:MA-QF2A:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-02:MA-QF2B:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-02:MA-QD2B:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-03:MA-QF3:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-03:MA-QD3:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-04:MA-QF4:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-04:MA-QD4:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-01:MA-CH-1:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-01:MA-CV-1:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-01:MA-CH-2:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-01:MA-CV-2:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-02:MA-CH-1:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-02:MA-CV-1:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-02:MA-CH-2:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-02:MA-CV-2:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-04:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-04:MA-CV-1:RmpIncNrCycles-SP', _off, 0.0],
    ['TB-04:MA-CV-2:RmpIncNrCycles-SP', _off, 0.0],

    ['TB-Fam:MA-B:Energy-SP', 0.0, 0.0],
    ['TB-01:MA-QD1:KL-SP', 0.0, 0.0],
    ['TB-01:MA-QF1:KL-SP', 0.0, 0.0],
    ['TB-02:MA-QD2A:KL-SP', 0.0, 0.0],
    ['TB-02:MA-QF2A:KL-SP', 0.0, 0.0],
    ['TB-02:MA-QF2B:KL-SP', 0.0, 0.0],
    ['TB-02:MA-QD2B:KL-SP', 0.0, 0.0],
    ['TB-03:MA-QF3:KL-SP', 0.0, 0.0],
    ['TB-03:MA-QD3:KL-SP', 0.0, 0.0],
    ['TB-04:MA-QF4:KL-SP', 0.0, 0.0],
    ['TB-04:MA-QD4:KL-SP', 0.0, 0.0],
    ['TB-01:MA-CH-1:Kick-SP', 0.0, 0.0],
    ['TB-01:MA-CV-1:Kick-SP', 0.0, 0.0],
    ['TB-01:MA-CH-2:Kick-SP', 0.0, 0.0],
    ['TB-01:MA-CV-2:Kick-SP', 0.0, 0.0],
    ['TB-02:MA-CH-1:Kick-SP', 0.0, 0.0],
    ['TB-02:MA-CV-1:Kick-SP', 0.0, 0.0],
    ['TB-02:MA-CH-2:Kick-SP', 0.0, 0.0],
    ['TB-02:MA-CV-2:Kick-SP', 0.0, 0.0],
    ['TB-04:MA-CH:Kick-SP', 0.0, 0.0],
    ['TB-04:MA-CV-1:Kick-SP', 0.0, 0.0],
    ['TB-04:MA-CV-2:Kick-SP', 0.0, 0.0],
    ]

_pvs_tb_hl_timing = [
    ['RA-RaMO:TI-EVG:InjBOMode-Sel', 0, 0.0],
    ['RA-RaMO:TI-EVG:DigTBMode-Sel', 0, 0.0],

    ['RA-RaMO:TI-EVG:InjBODelayType-Sel', 0, 0.0],
    ['RA-RaMO:TI-EVG:DigTBDelayType-Sel', 0, 0.0],

    ['RA-RaMO:TI-EVG:InjBODelay-SP', 0.0, 0.0],
    ['RA-RaMO:TI-EVG:DigTBDelay-SP', 0.0, 0.0],

    ['TB-Glob:TI-Mags:State-Sel', 0, 0.0],
    ['TB-04:TI-InjSept:State-Sel', 0, 0.0],
    ['AS-Fam:TI-Scrn-TBBO:State-Sel', 0, 0.0],
    ['AS-Glob:TI-BPM-TBTS:State-Sel', 0, 0.0],
    ['AS-Glob:TI-Osc-InjBO:State-Sel', 0, 0.0],
    ['TB-Fam:TI-ICT-Digit:State-Sel', 0, 0.0],
    ['TB-Fam:TI-ICT-Integ:State-Sel', 0, 0.0],
    ['BO-01D:TI-InjKckr:State-Sel', 0, 0.0],
    ['AS-Glob:TI-FCT:State-Sel', 0, 0.0],

    ['TB-Glob:TI-Mags:Polarity-Sel', 0, 0.0],
    ['TB-04:TI-InjSept:Polarity-Sel', 0, 0.0],
    ['AS-Fam:TI-Scrn-TBBO:Polarity-Sel', 0, 0.0],
    ['AS-Glob:TI-BPM-TBTS:Polarity-Sel', 0, 0.0],
    ['AS-Glob:TI-Osc-InjBO:Polarity-Sel', 0, 0.0],
    ['TB-Fam:TI-ICT-Digit:Polarity-Sel', 0, 0.0],
    ['TB-Fam:TI-ICT-Integ:Polarity-Sel', 0, 0.0],
    ['BO-01D:TI-InjKckr:Polarity-Sel', 0, 0.0],
    ['AS-Glob:TI-FCT:Polarity-Sel', 0, 0.0],

    ['TB-Glob:TI-Mags:Src-Sel', 0, 0.0],
    ['TB-04:TI-InjSept:Src-Sel', 0, 0.0],
    ['AS-Fam:TI-Scrn-TBBO:Src-Sel', 0, 0.0],
    ['AS-Glob:TI-BPM-TBTS:Src-Sel', 0, 0.0],
    ['AS-Glob:TI-Osc-InjBO:Src-Sel', 0, 0.0],
    ['TB-Fam:TI-ICT-Digit:Src-Sel', 0, 0.0],
    ['TB-Fam:TI-ICT-Integ:Src-Sel', 0, 0.0],
    ['BO-01D:TI-InjKckr:Src-Sel', 0, 0.0],
    ['AS-Glob:TI-FCT:Src-Sel', 0, 0.0],

    ['TB-Glob:TI-Mags:NrPulses-SP', 0, 0.0],
    ['TB-04:TI-InjSept:NrPulses-SP', 0, 0.0],
    ['AS-Fam:TI-Scrn-TBBO:NrPulses-SP', 0, 0.0],
    ['AS-Glob:TI-BPM-TBTS:NrPulses-SP', 0, 0.0],
    ['AS-Glob:TI-Osc-InjBO:NrPulses-SP', 0, 0.0],
    ['TB-Fam:TI-ICT-Digit:NrPulses-SP', 0, 0.0],
    ['TB-Fam:TI-ICT-Integ:NrPulses-SP', 0, 0.0],
    ['BO-01D:TI-InjKckr:NrPulses-SP', 0, 0.0],
    ['AS-Glob:TI-FCT:NrPulses-SP', 0, 0.0],

    ['TB-Glob:TI-Mags:Duration-SP', 0.0, 0.0],
    ['TB-04:TI-InjSept:Duration-SP', 0.0, 0.0],
    ['AS-Fam:TI-Scrn-TBBO:Duration-SP', 0.0, 0.0],
    ['AS-Glob:TI-BPM-TBTS:Duration-SP', 0.0, 0.0],
    ['AS-Glob:TI-Osc-InjBO:Duration-SP', 0.0, 0.0],
    ['TB-Fam:TI-ICT-Digit:Duration-SP', 0.0, 0.0],
    ['TB-Fam:TI-ICT-Integ:Duration-SP', 0.0, 0.0],
    ['BO-01D:TI-InjKckr:Duration-SP', 0.0, 0.0],
    ['AS-Glob:TI-FCT:Duration-SP', 0.0, 0.0],

    ['TB-Glob:TI-Mags:Delay-SP', 0.0, 0.0],
    ['TB-04:TI-InjSept:Delay-SP', 0.0, 0.0],
    ['AS-Fam:TI-Scrn-TBBO:Delay-SP', 0.0, 0.0],
    ['AS-Glob:TI-BPM-TBTS:Delay-SP', 0.0, 0.0],
    ['AS-Glob:TI-Osc-InjBO:Delay-SP', 0.0, 0.0],
    ['TB-Fam:TI-ICT-Digit:Delay-SP', 0.0, 0.0],
    ['TB-Fam:TI-ICT-Integ:Delay-SP', 0.0, 0.0],
    ['BO-01D:TI-InjKckr:Delay-SP', 0.0, 0.0],
    ['AS-Glob:TI-FCT:Delay-SP', 0.0, 0.0],

    # ['TB-Glob:TI-Mags:ByPassIntlk-Sel', 0, 0.0],
    ['TB-04:TI-InjSept:ByPassIntlk-Sel', 0, 0.0],
    ['AS-Fam:TI-Scrn-TBBO:ByPassIntlk-Sel', 0, 0.0],
    # ['AS-Glob:TI-BPM-TBTS:ByPassIntlk-Sel', 0, 0.0],
    ['AS-Glob:TI-Osc-InjBO:ByPassIntlk-Sel', 0, 0.0],
    ['TB-Fam:TI-ICT-Digit:ByPassIntlk-Sel', 0, 0.0],
    ['TB-Fam:TI-ICT-Integ:ByPassIntlk-Sel', 0, 0.0],
    ['BO-01D:TI-InjKckr:ByPassIntlk-Sel', 0, 0.0],
    ['AS-Glob:TI-FCT:ByPassIntlk-Sel', 0, 0.0],

    # ['TB-Glob:TI-Mags:RFDelayType-Sel', 0, 0.0],
    # ['TB-04:TI-InjSept:RFDelayType-Sel', 0, 0.0],
    ['AS-Fam:TI-Scrn-TBBO:RFDelayType-Sel', 0, 0.0],
    # ['AS-Glob:TI-BPM-TBTS:RFDelayType-Sel', 0, 0.0],
    # ['AS-Glob:TI-Osc-InjBO:RFDelayType-Sel', 0, 0.0],
    # ['TB-Fam:TI-ICT-Digit:RFDelayType-Sel', 0, 0.0],
    # ['TB-Fam:TI-ICT-Integ:RFDelayType-Sel', 0, 0.0],
    # ['BO-01D:TI-InjKckr:RFDelayType-Sel', 0, 0.0],
    ['AS-Glob:TI-FCT:RFDelayType-Sel', 0, 0.0],
    ]

_pvs_bo_ma = [
    ['BO-Fam:MA-B:PwrState-Sel', _off, 0.0],
    ['BO-Fam:MA-QD:PwrState-Sel', _off, 0.0],
    ['BO-Fam:MA-QF:PwrState-Sel', _off, 0.0],
    ['BO-02D:MA-QS:PwrState-Sel', _off, 0.0],
    ['BO-Fam:MA-SD:PwrState-Sel', _off, 0.0],
    ['BO-Fam:MA-SF:PwrState-Sel', _off, 0.0],
    ['BO-01U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-03U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-05U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-07U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-09U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-11U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-13U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-15U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-17U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-19U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-21U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-23U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-25U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-27U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-29U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-31U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-33U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-35U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-37U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-39U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-41U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-43U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-45U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-47U:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-49D:MA-CH:PwrState-Sel', _off, 0.0],
    ['BO-01U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-03U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-05U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-07U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-09U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-11U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-13U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-15U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-17U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-19U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-21U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-23U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-25U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-27U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-29U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-31U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-33U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-35U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-37U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-39U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-41U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-43U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-45U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-47U:MA-CV:PwrState-Sel', _off, 0.0],
    ['BO-49U:MA-CV:PwrState-Sel', _off, 0.0],

    ['BO-Fam:MA-B:OpMode-Sel', _off, 0.0],
    ['BO-Fam:MA-QD:OpMode-Sel', _off, 0.0],
    ['BO-Fam:MA-QF:OpMode-Sel', _off, 0.0],
    ['BO-02D:MA-QS:OpMode-Sel', _off, 0.0],
    ['BO-Fam:MA-SD:OpMode-Sel', _off, 0.0],
    ['BO-Fam:MA-SF:OpMode-Sel', _off, 0.0],
    ['BO-01U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-03U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-05U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-07U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-09U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-11U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-13U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-15U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-17U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-19U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-21U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-23U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-25U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-27U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-29U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-31U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-33U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-35U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-37U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-39U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-41U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-43U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-45U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-47U:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-49D:MA-CH:OpMode-Sel', _off, 0.0],
    ['BO-01U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-03U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-05U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-07U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-09U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-11U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-13U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-15U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-17U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-19U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-21U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-23U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-25U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-27U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-29U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-31U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-33U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-35U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-37U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-39U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-41U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-43U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-45U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-47U:MA-CV:OpMode-Sel', _off, 0.0],
    ['BO-49U:MA-CV:OpMode-Sel', _off, 0.0],

    ['BO-Fam:MA-B:BSMPComm-Sel', _off, 0.0],
    ['BO-Fam:MA-QD:BSMPComm-Sel', _off, 0.0],
    ['BO-Fam:MA-QF:BSMPComm-Sel', _off, 0.0],
    ['BO-02D:MA-QS:BSMPComm-Sel', _off, 0.0],
    ['BO-Fam:MA-SD:BSMPComm-Sel', _off, 0.0],
    ['BO-Fam:MA-SF:BSMPComm-Sel', _off, 0.0],
    ['BO-01U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-03U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-05U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-07U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-09U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-11U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-13U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-15U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-17U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-19U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-21U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-23U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-25U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-27U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-29U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-31U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-33U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-35U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-37U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-39U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-41U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-43U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-45U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-47U:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-49D:MA-CH:BSMPComm-Sel', _off, 0.0],
    ['BO-01U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-03U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-05U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-07U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-09U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-11U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-13U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-15U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-17U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-19U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-21U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-23U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-25U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-27U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-29U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-31U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-33U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-35U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-37U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-39U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-41U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-43U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-45U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-47U:MA-CV:BSMPComm-Sel', _off, 0.0],
    ['BO-49U:MA-CV:BSMPComm-Sel', _off, 0.0],

    ['BO-Fam:MA-B:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-Fam:MA-QD:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-Fam:MA-QF:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-02D:MA-QS:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-Fam:MA-SD:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-Fam:MA-SF:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-01U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-03U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-05U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-07U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-09U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-11U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-13U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-15U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-17U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-19U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-21U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-23U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-25U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-27U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-29U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-31U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-33U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-35U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-37U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-39U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-41U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-43U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-45U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-47U:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-49D:MA-CH:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-01U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-03U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-05U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-07U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-09U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-11U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-13U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-15U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-17U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-19U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-21U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-23U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-25U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-27U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-29U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-31U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-33U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-35U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-37U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-39U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-41U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-43U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-45U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-47U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],
    ['BO-49U:MA-CV:RmpIncNrCycles-SP', _off, 0.0],

    ['BO-Fam:MA-B:Energy-SP', +0.150, 0.0],  # [Energy: GeV]
    ['BO-Fam:MA-QD:KL', +0.0011197961538728, 0.0],  # [KL: 1/m]
    ['BO-Fam:MA-QF:KL', +0.3770999232791374, 0.0],  # [KL: 1/m]
    ['BO-02D:MA-QS:KL', +0.0, 0.0],  # [KL: 1/m] (skew quadrupole)
    ['BO-Fam:MA-SD:SL-SP', +0.5258382119529604, 0.0],  # [SL: 1/m^2]
    ['BO-Fam:MA-SF:SL-SP', +1.1898514030258744, 0.0],  # [SL: 1/m^2]
    ['BO-01U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-03U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-05U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-07U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-09U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-11U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-13U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-15U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-17U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-19U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-21U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-23U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-25U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-27U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-29U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-31U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-33U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-35U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-37U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-39U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-41U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-43U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-45U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-47U:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-49D:MA-CH:Kick-SP', +0.0, 0.0],
    ['BO-01U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-03U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-05U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-07U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-09U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-11U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-13U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-15U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-17U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-19U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-21U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-23U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-25U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-27U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-29U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-31U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-33U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-35U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-37U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-39U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-41U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-43U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-45U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-47U:MA-CV:Kick-SP', +0.0, 0.0],
    ['BO-49U:MA-CV:Kick-SP', +0.0, 0.0],
    ]

_pvs_bo_hl_timing = [
    ['RA-RaMO:TI-EVG:InjBOMode-Sel', 0, 0.0],
    ['RA-RaMO:TI-EVG:RmpBOMode-Sel', 0, 0.0],
    ['RA-RaMO:TI-EVG:DIGBOMode-Sel', 0, 0.0],
    ['RA-RaMO:TI-EVG:OrbBOMode-Sel', 0, 0.0],

    ['RA-RaMO:TI-EVG:InjBODelayType-Sel', 0, 0.0],
    ['RA-RaMO:TI-EVG:RmpBODelayType-Sel', 0, 0.0],
    ['RA-RaMO:TI-EVG:DIGBODelayType-Sel', 0, 0.0],
    ['RA-RaMO:TI-EVG:OrbBODelayType-Sel', 0, 0.0],

    ['RA-RaMO:TI-EVG:InjBODelay-SP', 0.0, 0.0],
    ['RA-RaMO:TI-EVG:RmpBODelay-SP', 0.0, 0.0],
    ['RA-RaMO:TI-EVG:DIGBODelay-SP', 0.0, 0.0],
    ['RA-RaMO:TI-EVG:OrbBODelay-SP', 0.0, 0.0],

    ['BO-01D:TI-InjKckr:State-Sel', 0, 0.0],
    ['BO-35D:TI-DCCT:State-Sel', 0, 0.0],
    ['BO-48D:TI-EjeKckr:State-Sel', 0, 0.0],
    ['BO-Glob:TI-Corrs:State-Sel', 0, 0.0],
    ['BO-Glob:TI-LLRF-PsMtn:State-Sel', 0, 0.0],
    ['BO-Glob:TI-LLRF-Rmp:State-Sel', 0, 0.0],
    ['BO-Glob:TI-Mags:State-Sel', 0, 0.0],
    ['BO-Glob:TI-TuneProc:State-Sel', 0, 0.0],
    ['AS-Glob:TI-BPM-SIBO:State-Sel', 0, 0.0],
    ['AS-Glob:TI-Osc-InjBO:State-Sel', 0, 0.0],

    ['BO-01D:TI-InjKckr:Polarity-Sel', 0, 0.0],
    ['BO-35D:TI-DCCT:Polarity-Sel', 0, 0.0],
    ['BO-48D:TI-EjeKckr:Polarity-Sel', 0, 0.0],
    ['BO-Glob:TI-Corrs:Polarity-Sel', 0, 0.0],
    ['BO-Glob:TI-LLRF-PsMtn:Polarity-Sel', 0, 0.0],
    ['BO-Glob:TI-LLRF-Rmp:Polarity-Sel', 0, 0.0],
    ['BO-Glob:TI-Mags:Polarity-Sel', 0, 0.0],
    ['BO-Glob:TI-TuneProc:Polarity-Sel', 0, 0.0],
    ['AS-Glob:TI-BPM-SIBO:Polarity-Sel', 0, 0.0],
    ['AS-Glob:TI-Osc-InjBO:Polarity-Sel', 0, 0.0],

    ['BO-01D:TI-InjKckr:Src-Sel', 0, 0.0],
    ['BO-35D:TI-DCCT:Src-Sel', 0, 0.0],
    ['BO-48D:TI-EjeKckr:Src-Sel', 0, 0.0],
    ['BO-Glob:TI-Corrs:Src-Sel', 0, 0.0],
    ['BO-Glob:TI-LLRF-PsMtn:Src-Sel', 0, 0.0],
    ['BO-Glob:TI-LLRF-Rmp:Src-Sel', 0, 0.0],
    ['BO-Glob:TI-Mags:Src-Sel', 0, 0.0],
    ['BO-Glob:TI-TuneProc:Src-Sel', 0, 0.0],
    ['AS-Glob:TI-BPM-SIBO:Src-Sel', 0, 0.0],
    ['AS-Glob:TI-Osc-InjBO:Src-Sel', 0, 0.0],

    ['BO-01D:TI-InjKckr:NrPulses-SP', 0, 0.0],
    ['BO-35D:TI-DCCT:NrPulses-SP', 0, 0.0],
    ['BO-48D:TI-EjeKckr:NrPulses-SP', 0, 0.0],
    ['BO-Glob:TI-Corrs:NrPulses-SP', 0, 0.0],
    ['BO-Glob:TI-LLRF-PsMtn:NrPulses-SP', 0, 0.0],
    ['BO-Glob:TI-LLRF-Rmp:NrPulses-SP', 0, 0.0],
    ['BO-Glob:TI-Mags:NrPulses-SP', 0, 0.0],
    ['BO-Glob:TI-TuneProc:NrPulses-SP', 0, 0.0],
    ['AS-Glob:TI-BPM-SIBO:NrPulses-SP', 0, 0.0],
    ['AS-Glob:TI-Osc-InjBO:NrPulses-SP', 0, 0.0],

    ['BO-01D:TI-InjKckr:Duration-SP', 0.0, 0.0],
    ['BO-35D:TI-DCCT:Duration-SP', 0.0, 0.0],
    ['BO-48D:TI-EjeKckr:Duration-SP', 0.0, 0.0],
    ['BO-Glob:TI-Corrs:Duration-SP', 0.0, 0.0],
    ['BO-Glob:TI-LLRF-PsMtn:Duration-SP', 0.0, 0.0],
    ['BO-Glob:TI-LLRF-Rmp:Duration-SP', 0.0, 0.0],
    ['BO-Glob:TI-Mags:Duration-SP', 0.0, 0.0],
    ['BO-Glob:TI-TuneProc:Duration-SP', 0.0, 0.0],
    ['AS-Glob:TI-BPM-SIBO:Duration-SP', 0.0, 0.0],
    ['AS-Glob:TI-Osc-InjBO:Duration-SP', 0.0, 0.0],

    ['BO-01D:TI-InjKckr:Delay-SP', 0.0, 0.0],
    ['BO-35D:TI-DCCT:Delay-SP', 0.0, 0.0],
    ['BO-48D:TI-EjeKckr:Delay-SP', 0.0, 0.0],
    ['BO-Glob:TI-Corrs:Delay-SP', 0.0, 0.0],
    ['BO-Glob:TI-LLRF-PsMtn:Delay-SP', 0.0, 0.0],
    ['BO-Glob:TI-LLRF-Rmp:Delay-SP', 0.0, 0.0],
    ['BO-Glob:TI-Mags:Delay-SP', 0.0, 0.0],
    ['BO-Glob:TI-TuneProc:Delay-SP', 0.0, 0.0],
    ['AS-Glob:TI-BPM-SIBO:Delay-SP', 0.0, 0.0],
    ['AS-Glob:TI-Osc-InjBO:Delay-SP', 0.0, 0.0],

    ['BO-01D:TI-InjKckr:ByPassIntlk-Sel', 0, 0.0],
    ['BO-35D:TI-DCCT:ByPassIntlk-Sel', 0, 0.0],
    ['BO-48D:TI-EjeKckr:ByPassIntlk-Sel', 0, 0.0],
    # ['BO-Glob:TI-Corrs:ByPassIntlk-Sel', 0, 0.0],
    ['BO-Glob:TI-LLRF-PsMtn:ByPassIntlk-Sel', 0, 0.0],
    ['BO-Glob:TI-LLRF-Rmp:ByPassIntlk-Sel', 0, 0.0],
    ['BO-Glob:TI-Mags:ByPassIntlk-Sel', 0, 0.0],
    ['BO-Glob:TI-TuneProc:ByPassIntlk-Sel', 0, 0.0],
    # ['AS-Glob:TI-BPM-SIBO:ByPassIntlk-Sel', 0, 0.0],
    ['AS-Glob:TI-Osc-InjBO:ByPassIntlk-Sel', 0, 0.0],

    # ['BO-01D:TI-InjKckr:RFDelayType-Sel', 0, 0.0],
    ['BO-35D:TI-DCCT:RFDelayType-Sel', 0, 0.0],
    ['BO-48D:TI-EjeKckr:RFDelayType-Sel', 0, 0.0],
    # ['BO-Glob:TI-Corrs:RFDelayType-Sel', 0, 0.0],
    ['BO-Glob:TI-LLRF-PsMtn:RFDelayType-Sel', 0, 0.0],
    ['BO-Glob:TI-LLRF-Rmp:RFDelayType-Sel', 0, 0.0],
    # ['BO-Glob:TI-Mags:RFDelayType-Sel', 0, 0.0],
    ['BO-Glob:TI-TuneProc:RFDelayType-Sel', 0, 0.0],
    # ['AS-Glob:TI-BPM-SIBO:RFDelayType-Sel', 0, 0.0],
    # ['AS-Glob:TI-Osc-InjBO:RFDelayType-Sel', 0, 0.0],
    ]

_template_dict = {
    'pvs': \
        _pvs_li_llrf + _pvs_li_hl_timing + _pvs_li_pwrsupplies + \
        _pvs_tb_ma + _pvs_tb_hl_timing + \
        _pvs_bo_ma + _pvs_bo_hl_timing
}
