"""LI low level RF configuration."""
from copy import deepcopy as _dcopy


def get_dict():
    """Return configuration type dictionary."""
    module_name = __name__.split('.')[-1]
    _dict = {
        'config_type_name': module_name,
        'value': _dcopy(_template_dict)
    }
    return _dict


# When using this type of configuration to set the machine,
# the list of PVs should be processed in the same order they are stored
# in the configuration. The second numeric parameter in the pair is the
# delay [s] the client should wait before setting the next PV.


_template_dict = {
    'pvs': [
        ['LA-RF:LLRF:BUN1:SET_STREAM', 0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_CH1_DELAY', 0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_CH2_DELAY', 0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_CH7_DELAY', 0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_CH8_DELAY', 0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_TRIGGER_DELAY', 0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_AMP', 0.0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_PHASE', 0.0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_FB_MODE', 0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_KP', 0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_KI', 0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_EXTERNAL_TRIGGER_ENABLE', 0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_INTEGRAL_ENABLE', 0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_CH1_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_CH2_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_CH7_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_CH8_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_FBLOOP_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_FBLOOP_AMP_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_CH1_ADT', 0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_CH2_ADT', 0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_CH7_ADT', 0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_CH8_ADT', 0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_VM_ADT', 0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_CH1_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_CH2_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_CH7_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_CH8_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_PID_MODE', 0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_PID_KP', 0, 0.0],
        ['LA-RF:LLRF:BUN1:SET_PID_KI', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_STREAM', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH1_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH2_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH3_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH4_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH5_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH6_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH7_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH8_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH9_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_TRIGGER_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_AMP', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_PHASE', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_FB_MODE', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_KP', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_KI', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_EXTERNAL_TRIGGER_ENABLE', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_INTEGRAL_ENABLE', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_FBLOOP_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_FBLOOP_AMP_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH1_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH2_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH3_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH4_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH5_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH6_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH7_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH8_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH9_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_FBLOOP_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_FBLOOP_AMP_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH1_ADT', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH2_ADT', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH3_ADT', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH4_ADT', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH5_ADT', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH6_ADT', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH7_ADT', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH8_ADT', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_VM_ADT', 0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH1_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH2_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH3_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH4_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH5_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH6_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH7_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH8_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_CH9_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:KLY1:SET_SHIF_MOTOR_ANGLE', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_STREAM', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH1_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH2_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH3_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH4_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH5_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH6_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH7_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH8_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH9_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_TRIGGER_DELAY', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_AMP', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_PHASE', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_FB_MODE', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_KP', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_KI', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_EXTERNAL_TRIGGER_ENABLE', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_INTEGRAL_ENABLE', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_FBLOOP_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_FBLOOP_AMP_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH1_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH2_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH3_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH4_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH5_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH6_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH7_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH8_PHASE_CORR', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH1_ADT', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH2_ADT', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH3_ADT', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH4_ADT', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH5_ADT', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH6_ADT', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH7_ADT', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH8_ADT', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_VM_ADT', 0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH1_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH2_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH3_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH4_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH5_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH6_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH7_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH8_ATT', 0.0, 0.0],
        ['LA-RF:LLRF:KLY2:SET_CH9_ATT', 0.0, 0.0],
    ]
}
