name: Publish siriuspy to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.SIRIUSPY_PYPI_TOKEN }}
        run: |
          git describe --tags | sed -e 's/^v//g' > VERSION
          cd siriuspy
          python -m build
          twine upload dist/*
          cd ..
